// Code generated by ent, DO NOT EDIT.

package dictionaryindexmanifest

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the dictionaryindexmanifest type in the database.
	Label = "dictionary_index_manifest"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDictionaryName holds the string denoting the dictionary_name field in the database.
	FieldDictionaryName = "dictionary_name"
	// FieldSourcePath holds the string denoting the source_path field in the database.
	FieldSourcePath = "source_path"
	// FieldFingerprint holds the string denoting the fingerprint field in the database.
	FieldFingerprint = "fingerprint"
	// FieldSchemaVersion holds the string denoting the schema_version field in the database.
	FieldSchemaVersion = "schema_version"
	// FieldBuiltAt holds the string denoting the built_at field in the database.
	FieldBuiltAt = "built_at"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// Table holds the table name of the dictionaryindexmanifest in the database.
	Table = "dictionary_index_manifests"
)

// Columns holds all SQL columns for dictionaryindexmanifest fields.
var Columns = []string{
	FieldID,
	FieldDictionaryName,
	FieldSourcePath,
	FieldFingerprint,
	FieldSchemaVersion,
	FieldBuiltAt,
	FieldExpiresAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DictionaryNameValidator is a validator for the "dictionary_name" field. It is called by the builders before save.
	DictionaryNameValidator func(string) error
	// DefaultSourcePath holds the default value on creation for the "source_path" field.
	DefaultSourcePath string
	// DefaultFingerprint holds the default value on creation for the "fingerprint" field.
	DefaultFingerprint string
	// DefaultSchemaVersion holds the default value on creation for the "schema_version" field.
	DefaultSchemaVersion string
)

// OrderOption defines the ordering options for the DictionaryIndexManifest queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDictionaryName orders the results by the dictionary_name field.
func ByDictionaryName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDictionaryName, opts...).ToFunc()
}

// BySourcePath orders the results by the source_path field.
func BySourcePath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourcePath, opts...).ToFunc()
}

// ByFingerprint orders the results by the fingerprint field.
func ByFingerprint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFingerprint, opts...).ToFunc()
}

// BySchemaVersion orders the results by the schema_version field.
func BySchemaVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSchemaVersion, opts...).ToFunc()
}

// ByBuiltAt orders the results by the built_at field.
func ByBuiltAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBuiltAt, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}
