// Code generated by ent, DO NOT EDIT.

package dictionaryindexmanifest

import (
	"owl/backend/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldLTE(FieldID, id))
}

// DictionaryName applies equality check predicate on the "dictionary_name" field. It's identical to DictionaryNameEQ.
func DictionaryName(v string) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldEQ(FieldDictionaryName, v))
}

// SourcePath applies equality check predicate on the "source_path" field. It's identical to SourcePathEQ.
func SourcePath(v string) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldEQ(FieldSourcePath, v))
}

// Fingerprint applies equality check predicate on the "fingerprint" field. It's identical to FingerprintEQ.
func Fingerprint(v string) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldEQ(FieldFingerprint, v))
}

// SchemaVersion applies equality check predicate on the "schema_version" field. It's identical to SchemaVersionEQ.
func SchemaVersion(v string) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldEQ(FieldSchemaVersion, v))
}

// BuiltAt applies equality check predicate on the "built_at" field. It's identical to BuiltAtEQ.
func BuiltAt(v time.Time) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldEQ(FieldBuiltAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldEQ(FieldExpiresAt, v))
}

// DictionaryNameEQ applies the EQ predicate on the "dictionary_name" field.
func DictionaryNameEQ(v string) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldEQ(FieldDictionaryName, v))
}

// DictionaryNameNEQ applies the NEQ predicate on the "dictionary_name" field.
func DictionaryNameNEQ(v string) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldNEQ(FieldDictionaryName, v))
}

// DictionaryNameIn applies the In predicate on the "dictionary_name" field.
func DictionaryNameIn(vs ...string) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldIn(FieldDictionaryName, vs...))
}

// DictionaryNameNotIn applies the NotIn predicate on the "dictionary_name" field.
func DictionaryNameNotIn(vs ...string) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldNotIn(FieldDictionaryName, vs...))
}

// DictionaryNameGT applies the GT predicate on the "dictionary_name" field.
func DictionaryNameGT(v string) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldGT(FieldDictionaryName, v))
}

// DictionaryNameGTE applies the GTE predicate on the "dictionary_name" field.
func DictionaryNameGTE(v string) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldGTE(FieldDictionaryName, v))
}

// DictionaryNameLT applies the LT predicate on the "dictionary_name" field.
func DictionaryNameLT(v string) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldLT(FieldDictionaryName, v))
}

// DictionaryNameLTE applies the LTE predicate on the "dictionary_name" field.
func DictionaryNameLTE(v string) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldLTE(FieldDictionaryName, v))
}

// DictionaryNameContains applies the Contains predicate on the "dictionary_name" field.
func DictionaryNameContains(v string) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldContains(FieldDictionaryName, v))
}

// DictionaryNameHasPrefix applies the HasPrefix predicate on the "dictionary_name" field.
func DictionaryNameHasPrefix(v string) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldHasPrefix(FieldDictionaryName, v))
}

// DictionaryNameHasSuffix applies the HasSuffix predicate on the "dictionary_name" field.
func DictionaryNameHasSuffix(v string) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldHasSuffix(FieldDictionaryName, v))
}

// DictionaryNameEqualFold applies the EqualFold predicate on the "dictionary_name" field.
func DictionaryNameEqualFold(v string) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldEqualFold(FieldDictionaryName, v))
}

// DictionaryNameContainsFold applies the ContainsFold predicate on the "dictionary_name" field.
func DictionaryNameContainsFold(v string) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldContainsFold(FieldDictionaryName, v))
}

// SourcePathEQ applies the EQ predicate on the "source_path" field.
func SourcePathEQ(v string) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldEQ(FieldSourcePath, v))
}

// SourcePathNEQ applies the NEQ predicate on the "source_path" field.
func SourcePathNEQ(v string) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldNEQ(FieldSourcePath, v))
}

// SourcePathIn applies the In predicate on the "source_path" field.
func SourcePathIn(vs ...string) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldIn(FieldSourcePath, vs...))
}

// SourcePathNotIn applies the NotIn predicate on the "source_path" field.
func SourcePathNotIn(vs ...string) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldNotIn(FieldSourcePath, vs...))
}

// SourcePathGT applies the GT predicate on the "source_path" field.
func SourcePathGT(v string) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldGT(FieldSourcePath, v))
}

// SourcePathGTE applies the GTE predicate on the "source_path" field.
func SourcePathGTE(v string) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldGTE(FieldSourcePath, v))
}

// SourcePathLT applies the LT predicate on the "source_path" field.
func SourcePathLT(v string) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldLT(FieldSourcePath, v))
}

// SourcePathLTE applies the LTE predicate on the "source_path" field.
func SourcePathLTE(v string) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldLTE(FieldSourcePath, v))
}

// SourcePathContains applies the Contains predicate on the "source_path" field.
func SourcePathContains(v string) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldContains(FieldSourcePath, v))
}

// SourcePathHasPrefix applies the HasPrefix predicate on the "source_path" field.
func SourcePathHasPrefix(v string) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldHasPrefix(FieldSourcePath, v))
}

// SourcePathHasSuffix applies the HasSuffix predicate on the "source_path" field.
func SourcePathHasSuffix(v string) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldHasSuffix(FieldSourcePath, v))
}

// SourcePathEqualFold applies the EqualFold predicate on the "source_path" field.
func SourcePathEqualFold(v string) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldEqualFold(FieldSourcePath, v))
}

// SourcePathContainsFold applies the ContainsFold predicate on the "source_path" field.
func SourcePathContainsFold(v string) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldContainsFold(FieldSourcePath, v))
}

// FingerprintEQ applies the EQ predicate on the "fingerprint" field.
func FingerprintEQ(v string) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldEQ(FieldFingerprint, v))
}

// FingerprintNEQ applies the NEQ predicate on the "fingerprint" field.
func FingerprintNEQ(v string) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldNEQ(FieldFingerprint, v))
}

// FingerprintIn applies the In predicate on the "fingerprint" field.
func FingerprintIn(vs ...string) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldIn(FieldFingerprint, vs...))
}

// FingerprintNotIn applies the NotIn predicate on the "fingerprint" field.
func FingerprintNotIn(vs ...string) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldNotIn(FieldFingerprint, vs...))
}

// FingerprintGT applies the GT predicate on the "fingerprint" field.
func FingerprintGT(v string) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldGT(FieldFingerprint, v))
}

// FingerprintGTE applies the GTE predicate on the "fingerprint" field.
func FingerprintGTE(v string) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldGTE(FieldFingerprint, v))
}

// FingerprintLT applies the LT predicate on the "fingerprint" field.
func FingerprintLT(v string) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldLT(FieldFingerprint, v))
}

// FingerprintLTE applies the LTE predicate on the "fingerprint" field.
func FingerprintLTE(v string) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldLTE(FieldFingerprint, v))
}

// FingerprintContains applies the Contains predicate on the "fingerprint" field.
func FingerprintContains(v string) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldContains(FieldFingerprint, v))
}

// FingerprintHasPrefix applies the HasPrefix predicate on the "fingerprint" field.
func FingerprintHasPrefix(v string) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldHasPrefix(FieldFingerprint, v))
}

// FingerprintHasSuffix applies the HasSuffix predicate on the "fingerprint" field.
func FingerprintHasSuffix(v string) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldHasSuffix(FieldFingerprint, v))
}

// FingerprintEqualFold applies the EqualFold predicate on the "fingerprint" field.
func FingerprintEqualFold(v string) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldEqualFold(FieldFingerprint, v))
}

// FingerprintContainsFold applies the ContainsFold predicate on the "fingerprint" field.
func FingerprintContainsFold(v string) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldContainsFold(FieldFingerprint, v))
}

// SchemaVersionEQ applies the EQ predicate on the "schema_version" field.
func SchemaVersionEQ(v string) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldEQ(FieldSchemaVersion, v))
}

// SchemaVersionNEQ applies the NEQ predicate on the "schema_version" field.
func SchemaVersionNEQ(v string) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldNEQ(FieldSchemaVersion, v))
}

// SchemaVersionIn applies the In predicate on the "schema_version" field.
func SchemaVersionIn(vs ...string) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldIn(FieldSchemaVersion, vs...))
}

// SchemaVersionNotIn applies the NotIn predicate on the "schema_version" field.
func SchemaVersionNotIn(vs ...string) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldNotIn(FieldSchemaVersion, vs...))
}

// SchemaVersionGT applies the GT predicate on the "schema_version" field.
func SchemaVersionGT(v string) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldGT(FieldSchemaVersion, v))
}

// SchemaVersionGTE applies the GTE predicate on the "schema_version" field.
func SchemaVersionGTE(v string) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldGTE(FieldSchemaVersion, v))
}

// SchemaVersionLT applies the LT predicate on the "schema_version" field.
func SchemaVersionLT(v string) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldLT(FieldSchemaVersion, v))
}

// SchemaVersionLTE applies the LTE predicate on the "schema_version" field.
func SchemaVersionLTE(v string) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldLTE(FieldSchemaVersion, v))
}

// SchemaVersionContains applies the Contains predicate on the "schema_version" field.
func SchemaVersionContains(v string) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldContains(FieldSchemaVersion, v))
}

// SchemaVersionHasPrefix applies the HasPrefix predicate on the "schema_version" field.
func SchemaVersionHasPrefix(v string) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldHasPrefix(FieldSchemaVersion, v))
}

// SchemaVersionHasSuffix applies the HasSuffix predicate on the "schema_version" field.
func SchemaVersionHasSuffix(v string) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldHasSuffix(FieldSchemaVersion, v))
}

// SchemaVersionEqualFold applies the EqualFold predicate on the "schema_version" field.
func SchemaVersionEqualFold(v string) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldEqualFold(FieldSchemaVersion, v))
}

// SchemaVersionContainsFold applies the ContainsFold predicate on the "schema_version" field.
func SchemaVersionContainsFold(v string) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldContainsFold(FieldSchemaVersion, v))
}

// BuiltAtEQ applies the EQ predicate on the "built_at" field.
func BuiltAtEQ(v time.Time) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldEQ(FieldBuiltAt, v))
}

// BuiltAtNEQ applies the NEQ predicate on the "built_at" field.
func BuiltAtNEQ(v time.Time) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldNEQ(FieldBuiltAt, v))
}

// BuiltAtIn applies the In predicate on the "built_at" field.
func BuiltAtIn(vs ...time.Time) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldIn(FieldBuiltAt, vs...))
}

// BuiltAtNotIn applies the NotIn predicate on the "built_at" field.
func BuiltAtNotIn(vs ...time.Time) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldNotIn(FieldBuiltAt, vs...))
}

// BuiltAtGT applies the GT predicate on the "built_at" field.
func BuiltAtGT(v time.Time) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldGT(FieldBuiltAt, v))
}

// BuiltAtGTE applies the GTE predicate on the "built_at" field.
func BuiltAtGTE(v time.Time) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldGTE(FieldBuiltAt, v))
}

// BuiltAtLT applies the LT predicate on the "built_at" field.
func BuiltAtLT(v time.Time) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldLT(FieldBuiltAt, v))
}

// BuiltAtLTE applies the LTE predicate on the "built_at" field.
func BuiltAtLTE(v time.Time) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldLTE(FieldBuiltAt, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.FieldNotNull(FieldExpiresAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DictionaryIndexManifest) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DictionaryIndexManifest) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DictionaryIndexManifest) predicate.DictionaryIndexManifest {
	return predicate.DictionaryIndexManifest(sql.NotPredicates(p))
}
