// Code generated by ent, DO NOT EDIT.

package user

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldPasswordHash holds the string denoting the password_hash field in the database.
	FieldPasswordHash = "password_hash"
	// FieldIsAdmin holds the string denoting the is_admin field in the database.
	FieldIsAdmin = "is_admin"
	// FieldLanguage holds the string denoting the language field in the database.
	FieldLanguage = "language"
	// FieldTheme holds the string denoting the theme field in the database.
	FieldTheme = "theme"
	// FieldFontMode holds the string denoting the font_mode field in the database.
	FieldFontMode = "font_mode"
	// FieldCustomFontName holds the string denoting the custom_font_name field in the database.
	FieldCustomFontName = "custom_font_name"
	// FieldCustomFontPath holds the string denoting the custom_font_path field in the database.
	FieldCustomFontPath = "custom_font_path"
	// FieldCustomFontFamily holds the string denoting the custom_font_family field in the database.
	FieldCustomFontFamily = "custom_font_family"
	// EdgeDictionaries holds the string denoting the dictionaries edge name in mutations.
	EdgeDictionaries = "dictionaries"
	// Table holds the table name of the user in the database.
	Table = "users"
	// DictionariesTable is the table that holds the dictionaries relation/edge.
	DictionariesTable = "dictionaries"
	// DictionariesInverseTable is the table name for the Dictionary entity.
	// It exists in this package in order to avoid circular dependency with the "dictionary" package.
	DictionariesInverseTable = "dictionaries"
	// DictionariesColumn is the table column denoting the dictionaries relation/edge.
	DictionariesColumn = "user_dictionaries"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldUsername,
	FieldPasswordHash,
	FieldIsAdmin,
	FieldLanguage,
	FieldTheme,
	FieldFontMode,
	FieldCustomFontName,
	FieldCustomFontPath,
	FieldCustomFontFamily,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	UsernameValidator func(string) error
	// PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	PasswordHashValidator func(string) error
	// DefaultIsAdmin holds the default value on creation for the "is_admin" field.
	DefaultIsAdmin bool
	// DefaultLanguage holds the default value on creation for the "language" field.
	DefaultLanguage string
	// DefaultTheme holds the default value on creation for the "theme" field.
	DefaultTheme string
	// DefaultFontMode holds the default value on creation for the "font_mode" field.
	DefaultFontMode string
	// DefaultCustomFontName holds the default value on creation for the "custom_font_name" field.
	DefaultCustomFontName string
	// DefaultCustomFontPath holds the default value on creation for the "custom_font_path" field.
	DefaultCustomFontPath string
	// DefaultCustomFontFamily holds the default value on creation for the "custom_font_family" field.
	DefaultCustomFontFamily string
)

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUsername orders the results by the username field.
func ByUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsername, opts...).ToFunc()
}

// ByPasswordHash orders the results by the password_hash field.
func ByPasswordHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPasswordHash, opts...).ToFunc()
}

// ByIsAdmin orders the results by the is_admin field.
func ByIsAdmin(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsAdmin, opts...).ToFunc()
}

// ByLanguage orders the results by the language field.
func ByLanguage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLanguage, opts...).ToFunc()
}

// ByTheme orders the results by the theme field.
func ByTheme(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTheme, opts...).ToFunc()
}

// ByFontMode orders the results by the font_mode field.
func ByFontMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFontMode, opts...).ToFunc()
}

// ByCustomFontName orders the results by the custom_font_name field.
func ByCustomFontName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCustomFontName, opts...).ToFunc()
}

// ByCustomFontPath orders the results by the custom_font_path field.
func ByCustomFontPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCustomFontPath, opts...).ToFunc()
}

// ByCustomFontFamily orders the results by the custom_font_family field.
func ByCustomFontFamily(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCustomFontFamily, opts...).ToFunc()
}

// ByDictionariesCount orders the results by dictionaries count.
func ByDictionariesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newDictionariesStep(), opts...)
	}
}

// ByDictionaries orders the results by dictionaries terms.
func ByDictionaries(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDictionariesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newDictionariesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DictionariesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, DictionariesTable, DictionariesColumn),
	)
}
