// Code generated by ent, DO NOT EDIT.

package user

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldDisplayName holds the string denoting the display_name field in the database.
	FieldDisplayName = "display_name"
	// FieldAvatarName holds the string denoting the avatar_name field in the database.
	FieldAvatarName = "avatar_name"
	// FieldAvatarPath holds the string denoting the avatar_path field in the database.
	FieldAvatarPath = "avatar_path"
	// FieldAvatarMime holds the string denoting the avatar_mime field in the database.
	FieldAvatarMime = "avatar_mime"
	// FieldPasswordHash holds the string denoting the password_hash field in the database.
	FieldPasswordHash = "password_hash"
	// FieldIsAdmin holds the string denoting the is_admin field in the database.
	FieldIsAdmin = "is_admin"
	// FieldLanguage holds the string denoting the language field in the database.
	FieldLanguage = "language"
	// FieldTheme holds the string denoting the theme field in the database.
	FieldTheme = "theme"
	// FieldFontMode holds the string denoting the font_mode field in the database.
	FieldFontMode = "font_mode"
	// FieldMcpTokenHash holds the string denoting the mcp_token_hash field in the database.
	FieldMcpTokenHash = "mcp_token_hash"
	// FieldMcpTokenHint holds the string denoting the mcp_token_hint field in the database.
	FieldMcpTokenHint = "mcp_token_hint"
	// EdgeDictionaries holds the string denoting the dictionaries edge name in mutations.
	EdgeDictionaries = "dictionaries"
	// EdgeSelectedFont holds the string denoting the selected_font edge name in mutations.
	EdgeSelectedFont = "selected_font"
	// Table holds the table name of the user in the database.
	Table = "users"
	// DictionariesTable is the table that holds the dictionaries relation/edge.
	DictionariesTable = "dictionaries"
	// DictionariesInverseTable is the table name for the Dictionary entity.
	// It exists in this package in order to avoid circular dependency with the "dictionary" package.
	DictionariesInverseTable = "dictionaries"
	// DictionariesColumn is the table column denoting the dictionaries relation/edge.
	DictionariesColumn = "user_dictionaries"
	// SelectedFontTable is the table that holds the selected_font relation/edge.
	SelectedFontTable = "users"
	// SelectedFontInverseTable is the table name for the Font entity.
	// It exists in this package in order to avoid circular dependency with the "font" package.
	SelectedFontInverseTable = "fonts"
	// SelectedFontColumn is the table column denoting the selected_font relation/edge.
	SelectedFontColumn = "user_selected_font"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldUsername,
	FieldDisplayName,
	FieldAvatarName,
	FieldAvatarPath,
	FieldAvatarMime,
	FieldPasswordHash,
	FieldIsAdmin,
	FieldLanguage,
	FieldTheme,
	FieldFontMode,
	FieldMcpTokenHash,
	FieldMcpTokenHint,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "users"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"user_selected_font",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	UsernameValidator func(string) error
	// DefaultDisplayName holds the default value on creation for the "display_name" field.
	DefaultDisplayName string
	// DefaultAvatarName holds the default value on creation for the "avatar_name" field.
	DefaultAvatarName string
	// DefaultAvatarPath holds the default value on creation for the "avatar_path" field.
	DefaultAvatarPath string
	// DefaultAvatarMime holds the default value on creation for the "avatar_mime" field.
	DefaultAvatarMime string
	// PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	PasswordHashValidator func(string) error
	// DefaultIsAdmin holds the default value on creation for the "is_admin" field.
	DefaultIsAdmin bool
	// DefaultLanguage holds the default value on creation for the "language" field.
	DefaultLanguage string
	// DefaultTheme holds the default value on creation for the "theme" field.
	DefaultTheme string
	// DefaultFontMode holds the default value on creation for the "font_mode" field.
	DefaultFontMode string
	// DefaultMcpTokenHash holds the default value on creation for the "mcp_token_hash" field.
	DefaultMcpTokenHash string
	// DefaultMcpTokenHint holds the default value on creation for the "mcp_token_hint" field.
	DefaultMcpTokenHint string
)

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUsername orders the results by the username field.
func ByUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsername, opts...).ToFunc()
}

// ByDisplayName orders the results by the display_name field.
func ByDisplayName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisplayName, opts...).ToFunc()
}

// ByAvatarName orders the results by the avatar_name field.
func ByAvatarName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAvatarName, opts...).ToFunc()
}

// ByAvatarPath orders the results by the avatar_path field.
func ByAvatarPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAvatarPath, opts...).ToFunc()
}

// ByAvatarMime orders the results by the avatar_mime field.
func ByAvatarMime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAvatarMime, opts...).ToFunc()
}

// ByPasswordHash orders the results by the password_hash field.
func ByPasswordHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPasswordHash, opts...).ToFunc()
}

// ByIsAdmin orders the results by the is_admin field.
func ByIsAdmin(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsAdmin, opts...).ToFunc()
}

// ByLanguage orders the results by the language field.
func ByLanguage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLanguage, opts...).ToFunc()
}

// ByTheme orders the results by the theme field.
func ByTheme(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTheme, opts...).ToFunc()
}

// ByFontMode orders the results by the font_mode field.
func ByFontMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFontMode, opts...).ToFunc()
}

// ByMcpTokenHash orders the results by the mcp_token_hash field.
func ByMcpTokenHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMcpTokenHash, opts...).ToFunc()
}

// ByMcpTokenHint orders the results by the mcp_token_hint field.
func ByMcpTokenHint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMcpTokenHint, opts...).ToFunc()
}

// ByDictionariesCount orders the results by dictionaries count.
func ByDictionariesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newDictionariesStep(), opts...)
	}
}

// ByDictionaries orders the results by dictionaries terms.
func ByDictionaries(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDictionariesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// BySelectedFontField orders the results by selected_font field.
func BySelectedFontField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSelectedFontStep(), sql.OrderByField(field, opts...))
	}
}
func newDictionariesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DictionariesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, DictionariesTable, DictionariesColumn),
	)
}
func newSelectedFontStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SelectedFontInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, SelectedFontTable, SelectedFontColumn),
	)
}
