// Code generated by ent, DO NOT EDIT.

package user

import (
	"owl/backend/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.User {
	return predicate.User(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.User {
	return predicate.User(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.User {
	return predicate.User(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.User {
	return predicate.User(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.User {
	return predicate.User(sql.FieldLTE(FieldID, id))
}

// Username applies equality check predicate on the "username" field. It's identical to UsernameEQ.
func Username(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUsername, v))
}

// DisplayName applies equality check predicate on the "display_name" field. It's identical to DisplayNameEQ.
func DisplayName(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldDisplayName, v))
}

// AvatarName applies equality check predicate on the "avatar_name" field. It's identical to AvatarNameEQ.
func AvatarName(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldAvatarName, v))
}

// AvatarPath applies equality check predicate on the "avatar_path" field. It's identical to AvatarPathEQ.
func AvatarPath(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldAvatarPath, v))
}

// AvatarMime applies equality check predicate on the "avatar_mime" field. It's identical to AvatarMimeEQ.
func AvatarMime(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldAvatarMime, v))
}

// PasswordHash applies equality check predicate on the "password_hash" field. It's identical to PasswordHashEQ.
func PasswordHash(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldPasswordHash, v))
}

// IsAdmin applies equality check predicate on the "is_admin" field. It's identical to IsAdminEQ.
func IsAdmin(v bool) predicate.User {
	return predicate.User(sql.FieldEQ(FieldIsAdmin, v))
}

// Language applies equality check predicate on the "language" field. It's identical to LanguageEQ.
func Language(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldLanguage, v))
}

// Theme applies equality check predicate on the "theme" field. It's identical to ThemeEQ.
func Theme(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldTheme, v))
}

// FontMode applies equality check predicate on the "font_mode" field. It's identical to FontModeEQ.
func FontMode(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldFontMode, v))
}

// RecentSearchLimit applies equality check predicate on the "recent_search_limit" field. It's identical to RecentSearchLimitEQ.
func RecentSearchLimit(v int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldRecentSearchLimit, v))
}

// McpTokenHash applies equality check predicate on the "mcp_token_hash" field. It's identical to McpTokenHashEQ.
func McpTokenHash(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldMcpTokenHash, v))
}

// McpTokenHint applies equality check predicate on the "mcp_token_hint" field. It's identical to McpTokenHintEQ.
func McpTokenHint(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldMcpTokenHint, v))
}

// UsernameEQ applies the EQ predicate on the "username" field.
func UsernameEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUsername, v))
}

// UsernameNEQ applies the NEQ predicate on the "username" field.
func UsernameNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldUsername, v))
}

// UsernameIn applies the In predicate on the "username" field.
func UsernameIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldUsername, vs...))
}

// UsernameNotIn applies the NotIn predicate on the "username" field.
func UsernameNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldUsername, vs...))
}

// UsernameGT applies the GT predicate on the "username" field.
func UsernameGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldUsername, v))
}

// UsernameGTE applies the GTE predicate on the "username" field.
func UsernameGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldUsername, v))
}

// UsernameLT applies the LT predicate on the "username" field.
func UsernameLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldUsername, v))
}

// UsernameLTE applies the LTE predicate on the "username" field.
func UsernameLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldUsername, v))
}

// UsernameContains applies the Contains predicate on the "username" field.
func UsernameContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldUsername, v))
}

// UsernameHasPrefix applies the HasPrefix predicate on the "username" field.
func UsernameHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldUsername, v))
}

// UsernameHasSuffix applies the HasSuffix predicate on the "username" field.
func UsernameHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldUsername, v))
}

// UsernameEqualFold applies the EqualFold predicate on the "username" field.
func UsernameEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldUsername, v))
}

// UsernameContainsFold applies the ContainsFold predicate on the "username" field.
func UsernameContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldUsername, v))
}

// DisplayNameEQ applies the EQ predicate on the "display_name" field.
func DisplayNameEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldDisplayName, v))
}

// DisplayNameNEQ applies the NEQ predicate on the "display_name" field.
func DisplayNameNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldDisplayName, v))
}

// DisplayNameIn applies the In predicate on the "display_name" field.
func DisplayNameIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldDisplayName, vs...))
}

// DisplayNameNotIn applies the NotIn predicate on the "display_name" field.
func DisplayNameNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldDisplayName, vs...))
}

// DisplayNameGT applies the GT predicate on the "display_name" field.
func DisplayNameGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldDisplayName, v))
}

// DisplayNameGTE applies the GTE predicate on the "display_name" field.
func DisplayNameGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldDisplayName, v))
}

// DisplayNameLT applies the LT predicate on the "display_name" field.
func DisplayNameLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldDisplayName, v))
}

// DisplayNameLTE applies the LTE predicate on the "display_name" field.
func DisplayNameLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldDisplayName, v))
}

// DisplayNameContains applies the Contains predicate on the "display_name" field.
func DisplayNameContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldDisplayName, v))
}

// DisplayNameHasPrefix applies the HasPrefix predicate on the "display_name" field.
func DisplayNameHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldDisplayName, v))
}

// DisplayNameHasSuffix applies the HasSuffix predicate on the "display_name" field.
func DisplayNameHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldDisplayName, v))
}

// DisplayNameEqualFold applies the EqualFold predicate on the "display_name" field.
func DisplayNameEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldDisplayName, v))
}

// DisplayNameContainsFold applies the ContainsFold predicate on the "display_name" field.
func DisplayNameContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldDisplayName, v))
}

// AvatarNameEQ applies the EQ predicate on the "avatar_name" field.
func AvatarNameEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldAvatarName, v))
}

// AvatarNameNEQ applies the NEQ predicate on the "avatar_name" field.
func AvatarNameNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldAvatarName, v))
}

// AvatarNameIn applies the In predicate on the "avatar_name" field.
func AvatarNameIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldAvatarName, vs...))
}

// AvatarNameNotIn applies the NotIn predicate on the "avatar_name" field.
func AvatarNameNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldAvatarName, vs...))
}

// AvatarNameGT applies the GT predicate on the "avatar_name" field.
func AvatarNameGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldAvatarName, v))
}

// AvatarNameGTE applies the GTE predicate on the "avatar_name" field.
func AvatarNameGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldAvatarName, v))
}

// AvatarNameLT applies the LT predicate on the "avatar_name" field.
func AvatarNameLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldAvatarName, v))
}

// AvatarNameLTE applies the LTE predicate on the "avatar_name" field.
func AvatarNameLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldAvatarName, v))
}

// AvatarNameContains applies the Contains predicate on the "avatar_name" field.
func AvatarNameContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldAvatarName, v))
}

// AvatarNameHasPrefix applies the HasPrefix predicate on the "avatar_name" field.
func AvatarNameHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldAvatarName, v))
}

// AvatarNameHasSuffix applies the HasSuffix predicate on the "avatar_name" field.
func AvatarNameHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldAvatarName, v))
}

// AvatarNameEqualFold applies the EqualFold predicate on the "avatar_name" field.
func AvatarNameEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldAvatarName, v))
}

// AvatarNameContainsFold applies the ContainsFold predicate on the "avatar_name" field.
func AvatarNameContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldAvatarName, v))
}

// AvatarPathEQ applies the EQ predicate on the "avatar_path" field.
func AvatarPathEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldAvatarPath, v))
}

// AvatarPathNEQ applies the NEQ predicate on the "avatar_path" field.
func AvatarPathNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldAvatarPath, v))
}

// AvatarPathIn applies the In predicate on the "avatar_path" field.
func AvatarPathIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldAvatarPath, vs...))
}

// AvatarPathNotIn applies the NotIn predicate on the "avatar_path" field.
func AvatarPathNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldAvatarPath, vs...))
}

// AvatarPathGT applies the GT predicate on the "avatar_path" field.
func AvatarPathGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldAvatarPath, v))
}

// AvatarPathGTE applies the GTE predicate on the "avatar_path" field.
func AvatarPathGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldAvatarPath, v))
}

// AvatarPathLT applies the LT predicate on the "avatar_path" field.
func AvatarPathLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldAvatarPath, v))
}

// AvatarPathLTE applies the LTE predicate on the "avatar_path" field.
func AvatarPathLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldAvatarPath, v))
}

// AvatarPathContains applies the Contains predicate on the "avatar_path" field.
func AvatarPathContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldAvatarPath, v))
}

// AvatarPathHasPrefix applies the HasPrefix predicate on the "avatar_path" field.
func AvatarPathHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldAvatarPath, v))
}

// AvatarPathHasSuffix applies the HasSuffix predicate on the "avatar_path" field.
func AvatarPathHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldAvatarPath, v))
}

// AvatarPathEqualFold applies the EqualFold predicate on the "avatar_path" field.
func AvatarPathEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldAvatarPath, v))
}

// AvatarPathContainsFold applies the ContainsFold predicate on the "avatar_path" field.
func AvatarPathContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldAvatarPath, v))
}

// AvatarMimeEQ applies the EQ predicate on the "avatar_mime" field.
func AvatarMimeEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldAvatarMime, v))
}

// AvatarMimeNEQ applies the NEQ predicate on the "avatar_mime" field.
func AvatarMimeNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldAvatarMime, v))
}

// AvatarMimeIn applies the In predicate on the "avatar_mime" field.
func AvatarMimeIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldAvatarMime, vs...))
}

// AvatarMimeNotIn applies the NotIn predicate on the "avatar_mime" field.
func AvatarMimeNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldAvatarMime, vs...))
}

// AvatarMimeGT applies the GT predicate on the "avatar_mime" field.
func AvatarMimeGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldAvatarMime, v))
}

// AvatarMimeGTE applies the GTE predicate on the "avatar_mime" field.
func AvatarMimeGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldAvatarMime, v))
}

// AvatarMimeLT applies the LT predicate on the "avatar_mime" field.
func AvatarMimeLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldAvatarMime, v))
}

// AvatarMimeLTE applies the LTE predicate on the "avatar_mime" field.
func AvatarMimeLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldAvatarMime, v))
}

// AvatarMimeContains applies the Contains predicate on the "avatar_mime" field.
func AvatarMimeContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldAvatarMime, v))
}

// AvatarMimeHasPrefix applies the HasPrefix predicate on the "avatar_mime" field.
func AvatarMimeHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldAvatarMime, v))
}

// AvatarMimeHasSuffix applies the HasSuffix predicate on the "avatar_mime" field.
func AvatarMimeHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldAvatarMime, v))
}

// AvatarMimeEqualFold applies the EqualFold predicate on the "avatar_mime" field.
func AvatarMimeEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldAvatarMime, v))
}

// AvatarMimeContainsFold applies the ContainsFold predicate on the "avatar_mime" field.
func AvatarMimeContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldAvatarMime, v))
}

// PasswordHashEQ applies the EQ predicate on the "password_hash" field.
func PasswordHashEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldPasswordHash, v))
}

// PasswordHashNEQ applies the NEQ predicate on the "password_hash" field.
func PasswordHashNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldPasswordHash, v))
}

// PasswordHashIn applies the In predicate on the "password_hash" field.
func PasswordHashIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldPasswordHash, vs...))
}

// PasswordHashNotIn applies the NotIn predicate on the "password_hash" field.
func PasswordHashNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldPasswordHash, vs...))
}

// PasswordHashGT applies the GT predicate on the "password_hash" field.
func PasswordHashGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldPasswordHash, v))
}

// PasswordHashGTE applies the GTE predicate on the "password_hash" field.
func PasswordHashGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldPasswordHash, v))
}

// PasswordHashLT applies the LT predicate on the "password_hash" field.
func PasswordHashLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldPasswordHash, v))
}

// PasswordHashLTE applies the LTE predicate on the "password_hash" field.
func PasswordHashLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldPasswordHash, v))
}

// PasswordHashContains applies the Contains predicate on the "password_hash" field.
func PasswordHashContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldPasswordHash, v))
}

// PasswordHashHasPrefix applies the HasPrefix predicate on the "password_hash" field.
func PasswordHashHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldPasswordHash, v))
}

// PasswordHashHasSuffix applies the HasSuffix predicate on the "password_hash" field.
func PasswordHashHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldPasswordHash, v))
}

// PasswordHashEqualFold applies the EqualFold predicate on the "password_hash" field.
func PasswordHashEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldPasswordHash, v))
}

// PasswordHashContainsFold applies the ContainsFold predicate on the "password_hash" field.
func PasswordHashContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldPasswordHash, v))
}

// IsAdminEQ applies the EQ predicate on the "is_admin" field.
func IsAdminEQ(v bool) predicate.User {
	return predicate.User(sql.FieldEQ(FieldIsAdmin, v))
}

// IsAdminNEQ applies the NEQ predicate on the "is_admin" field.
func IsAdminNEQ(v bool) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldIsAdmin, v))
}

// LanguageEQ applies the EQ predicate on the "language" field.
func LanguageEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldLanguage, v))
}

// LanguageNEQ applies the NEQ predicate on the "language" field.
func LanguageNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldLanguage, v))
}

// LanguageIn applies the In predicate on the "language" field.
func LanguageIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldLanguage, vs...))
}

// LanguageNotIn applies the NotIn predicate on the "language" field.
func LanguageNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldLanguage, vs...))
}

// LanguageGT applies the GT predicate on the "language" field.
func LanguageGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldLanguage, v))
}

// LanguageGTE applies the GTE predicate on the "language" field.
func LanguageGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldLanguage, v))
}

// LanguageLT applies the LT predicate on the "language" field.
func LanguageLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldLanguage, v))
}

// LanguageLTE applies the LTE predicate on the "language" field.
func LanguageLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldLanguage, v))
}

// LanguageContains applies the Contains predicate on the "language" field.
func LanguageContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldLanguage, v))
}

// LanguageHasPrefix applies the HasPrefix predicate on the "language" field.
func LanguageHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldLanguage, v))
}

// LanguageHasSuffix applies the HasSuffix predicate on the "language" field.
func LanguageHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldLanguage, v))
}

// LanguageEqualFold applies the EqualFold predicate on the "language" field.
func LanguageEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldLanguage, v))
}

// LanguageContainsFold applies the ContainsFold predicate on the "language" field.
func LanguageContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldLanguage, v))
}

// ThemeEQ applies the EQ predicate on the "theme" field.
func ThemeEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldTheme, v))
}

// ThemeNEQ applies the NEQ predicate on the "theme" field.
func ThemeNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldTheme, v))
}

// ThemeIn applies the In predicate on the "theme" field.
func ThemeIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldTheme, vs...))
}

// ThemeNotIn applies the NotIn predicate on the "theme" field.
func ThemeNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldTheme, vs...))
}

// ThemeGT applies the GT predicate on the "theme" field.
func ThemeGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldTheme, v))
}

// ThemeGTE applies the GTE predicate on the "theme" field.
func ThemeGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldTheme, v))
}

// ThemeLT applies the LT predicate on the "theme" field.
func ThemeLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldTheme, v))
}

// ThemeLTE applies the LTE predicate on the "theme" field.
func ThemeLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldTheme, v))
}

// ThemeContains applies the Contains predicate on the "theme" field.
func ThemeContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldTheme, v))
}

// ThemeHasPrefix applies the HasPrefix predicate on the "theme" field.
func ThemeHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldTheme, v))
}

// ThemeHasSuffix applies the HasSuffix predicate on the "theme" field.
func ThemeHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldTheme, v))
}

// ThemeEqualFold applies the EqualFold predicate on the "theme" field.
func ThemeEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldTheme, v))
}

// ThemeContainsFold applies the ContainsFold predicate on the "theme" field.
func ThemeContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldTheme, v))
}

// FontModeEQ applies the EQ predicate on the "font_mode" field.
func FontModeEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldFontMode, v))
}

// FontModeNEQ applies the NEQ predicate on the "font_mode" field.
func FontModeNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldFontMode, v))
}

// FontModeIn applies the In predicate on the "font_mode" field.
func FontModeIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldFontMode, vs...))
}

// FontModeNotIn applies the NotIn predicate on the "font_mode" field.
func FontModeNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldFontMode, vs...))
}

// FontModeGT applies the GT predicate on the "font_mode" field.
func FontModeGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldFontMode, v))
}

// FontModeGTE applies the GTE predicate on the "font_mode" field.
func FontModeGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldFontMode, v))
}

// FontModeLT applies the LT predicate on the "font_mode" field.
func FontModeLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldFontMode, v))
}

// FontModeLTE applies the LTE predicate on the "font_mode" field.
func FontModeLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldFontMode, v))
}

// FontModeContains applies the Contains predicate on the "font_mode" field.
func FontModeContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldFontMode, v))
}

// FontModeHasPrefix applies the HasPrefix predicate on the "font_mode" field.
func FontModeHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldFontMode, v))
}

// FontModeHasSuffix applies the HasSuffix predicate on the "font_mode" field.
func FontModeHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldFontMode, v))
}

// FontModeEqualFold applies the EqualFold predicate on the "font_mode" field.
func FontModeEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldFontMode, v))
}

// FontModeContainsFold applies the ContainsFold predicate on the "font_mode" field.
func FontModeContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldFontMode, v))
}

// RecentSearchLimitEQ applies the EQ predicate on the "recent_search_limit" field.
func RecentSearchLimitEQ(v int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldRecentSearchLimit, v))
}

// RecentSearchLimitNEQ applies the NEQ predicate on the "recent_search_limit" field.
func RecentSearchLimitNEQ(v int) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldRecentSearchLimit, v))
}

// RecentSearchLimitIn applies the In predicate on the "recent_search_limit" field.
func RecentSearchLimitIn(vs ...int) predicate.User {
	return predicate.User(sql.FieldIn(FieldRecentSearchLimit, vs...))
}

// RecentSearchLimitNotIn applies the NotIn predicate on the "recent_search_limit" field.
func RecentSearchLimitNotIn(vs ...int) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldRecentSearchLimit, vs...))
}

// RecentSearchLimitGT applies the GT predicate on the "recent_search_limit" field.
func RecentSearchLimitGT(v int) predicate.User {
	return predicate.User(sql.FieldGT(FieldRecentSearchLimit, v))
}

// RecentSearchLimitGTE applies the GTE predicate on the "recent_search_limit" field.
func RecentSearchLimitGTE(v int) predicate.User {
	return predicate.User(sql.FieldGTE(FieldRecentSearchLimit, v))
}

// RecentSearchLimitLT applies the LT predicate on the "recent_search_limit" field.
func RecentSearchLimitLT(v int) predicate.User {
	return predicate.User(sql.FieldLT(FieldRecentSearchLimit, v))
}

// RecentSearchLimitLTE applies the LTE predicate on the "recent_search_limit" field.
func RecentSearchLimitLTE(v int) predicate.User {
	return predicate.User(sql.FieldLTE(FieldRecentSearchLimit, v))
}

// McpTokenHashEQ applies the EQ predicate on the "mcp_token_hash" field.
func McpTokenHashEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldMcpTokenHash, v))
}

// McpTokenHashNEQ applies the NEQ predicate on the "mcp_token_hash" field.
func McpTokenHashNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldMcpTokenHash, v))
}

// McpTokenHashIn applies the In predicate on the "mcp_token_hash" field.
func McpTokenHashIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldMcpTokenHash, vs...))
}

// McpTokenHashNotIn applies the NotIn predicate on the "mcp_token_hash" field.
func McpTokenHashNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldMcpTokenHash, vs...))
}

// McpTokenHashGT applies the GT predicate on the "mcp_token_hash" field.
func McpTokenHashGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldMcpTokenHash, v))
}

// McpTokenHashGTE applies the GTE predicate on the "mcp_token_hash" field.
func McpTokenHashGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldMcpTokenHash, v))
}

// McpTokenHashLT applies the LT predicate on the "mcp_token_hash" field.
func McpTokenHashLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldMcpTokenHash, v))
}

// McpTokenHashLTE applies the LTE predicate on the "mcp_token_hash" field.
func McpTokenHashLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldMcpTokenHash, v))
}

// McpTokenHashContains applies the Contains predicate on the "mcp_token_hash" field.
func McpTokenHashContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldMcpTokenHash, v))
}

// McpTokenHashHasPrefix applies the HasPrefix predicate on the "mcp_token_hash" field.
func McpTokenHashHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldMcpTokenHash, v))
}

// McpTokenHashHasSuffix applies the HasSuffix predicate on the "mcp_token_hash" field.
func McpTokenHashHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldMcpTokenHash, v))
}

// McpTokenHashEqualFold applies the EqualFold predicate on the "mcp_token_hash" field.
func McpTokenHashEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldMcpTokenHash, v))
}

// McpTokenHashContainsFold applies the ContainsFold predicate on the "mcp_token_hash" field.
func McpTokenHashContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldMcpTokenHash, v))
}

// McpTokenHintEQ applies the EQ predicate on the "mcp_token_hint" field.
func McpTokenHintEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldMcpTokenHint, v))
}

// McpTokenHintNEQ applies the NEQ predicate on the "mcp_token_hint" field.
func McpTokenHintNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldMcpTokenHint, v))
}

// McpTokenHintIn applies the In predicate on the "mcp_token_hint" field.
func McpTokenHintIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldMcpTokenHint, vs...))
}

// McpTokenHintNotIn applies the NotIn predicate on the "mcp_token_hint" field.
func McpTokenHintNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldMcpTokenHint, vs...))
}

// McpTokenHintGT applies the GT predicate on the "mcp_token_hint" field.
func McpTokenHintGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldMcpTokenHint, v))
}

// McpTokenHintGTE applies the GTE predicate on the "mcp_token_hint" field.
func McpTokenHintGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldMcpTokenHint, v))
}

// McpTokenHintLT applies the LT predicate on the "mcp_token_hint" field.
func McpTokenHintLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldMcpTokenHint, v))
}

// McpTokenHintLTE applies the LTE predicate on the "mcp_token_hint" field.
func McpTokenHintLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldMcpTokenHint, v))
}

// McpTokenHintContains applies the Contains predicate on the "mcp_token_hint" field.
func McpTokenHintContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldMcpTokenHint, v))
}

// McpTokenHintHasPrefix applies the HasPrefix predicate on the "mcp_token_hint" field.
func McpTokenHintHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldMcpTokenHint, v))
}

// McpTokenHintHasSuffix applies the HasSuffix predicate on the "mcp_token_hint" field.
func McpTokenHintHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldMcpTokenHint, v))
}

// McpTokenHintEqualFold applies the EqualFold predicate on the "mcp_token_hint" field.
func McpTokenHintEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldMcpTokenHint, v))
}

// McpTokenHintContainsFold applies the ContainsFold predicate on the "mcp_token_hint" field.
func McpTokenHintContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldMcpTokenHint, v))
}

// HasDictionaries applies the HasEdge predicate on the "dictionaries" edge.
func HasDictionaries() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, DictionariesTable, DictionariesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDictionariesWith applies the HasEdge predicate on the "dictionaries" edge with a given conditions (other predicates).
func HasDictionariesWith(preds ...predicate.Dictionary) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newDictionariesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSelectedFont applies the HasEdge predicate on the "selected_font" edge.
func HasSelectedFont() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, SelectedFontTable, SelectedFontColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSelectedFontWith applies the HasEdge predicate on the "selected_font" edge with a given conditions (other predicates).
func HasSelectedFontWith(preds ...predicate.Font) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newSelectedFontStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.User) predicate.User {
	return predicate.User(sql.NotPredicates(p))
}
