// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Dictionary is the predicate function for dictionary builders.
type Dictionary func(*sql.Selector)

// Font is the predicate function for font builders.
type Font func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
