services:
  redis:
    image: redis/redis-stack-server:7.4.0-v8
    container_name: owl-redis-stack
    restart: unless-stopped
    volumes:
      - owl_redis_stack:/data

  owl:
    depends_on:
      - redis
    environment:
      OWL_REDIS_ADDR: redis:6379
      OWL_REDIS_SEARCH_ENABLED: 'true'

volumes:
  owl_redis_stack:
