// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"owl/backend/ent/dictionaryindexentry"
	"owl/backend/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DictionaryIndexEntryUpdate is the builder for updating DictionaryIndexEntry entities.
type DictionaryIndexEntryUpdate struct {
	config
	hooks    []Hook
	mutation *DictionaryIndexEntryMutation
}

// Where appends a list predicates to the DictionaryIndexEntryUpdate builder.
func (_u *DictionaryIndexEntryUpdate) Where(ps ...predicate.DictionaryIndexEntry) *DictionaryIndexEntryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDictionaryName sets the "dictionary_name" field.
func (_u *DictionaryIndexEntryUpdate) SetDictionaryName(v string) *DictionaryIndexEntryUpdate {
	_u.mutation.SetDictionaryName(v)
	return _u
}

// SetNillableDictionaryName sets the "dictionary_name" field if the given value is not nil.
func (_u *DictionaryIndexEntryUpdate) SetNillableDictionaryName(v *string) *DictionaryIndexEntryUpdate {
	if v != nil {
		_u.SetDictionaryName(*v)
	}
	return _u
}

// SetKeyword sets the "keyword" field.
func (_u *DictionaryIndexEntryUpdate) SetKeyword(v string) *DictionaryIndexEntryUpdate {
	_u.mutation.SetKeyword(v)
	return _u
}

// SetNillableKeyword sets the "keyword" field if the given value is not nil.
func (_u *DictionaryIndexEntryUpdate) SetNillableKeyword(v *string) *DictionaryIndexEntryUpdate {
	if v != nil {
		_u.SetKeyword(*v)
	}
	return _u
}

// SetNormalizedKeyword sets the "normalized_keyword" field.
func (_u *DictionaryIndexEntryUpdate) SetNormalizedKeyword(v string) *DictionaryIndexEntryUpdate {
	_u.mutation.SetNormalizedKeyword(v)
	return _u
}

// SetNillableNormalizedKeyword sets the "normalized_keyword" field if the given value is not nil.
func (_u *DictionaryIndexEntryUpdate) SetNillableNormalizedKeyword(v *string) *DictionaryIndexEntryUpdate {
	if v != nil {
		_u.SetNormalizedKeyword(*v)
	}
	return _u
}

// SetLookupKey sets the "lookup_key" field.
func (_u *DictionaryIndexEntryUpdate) SetLookupKey(v string) *DictionaryIndexEntryUpdate {
	_u.mutation.SetLookupKey(v)
	return _u
}

// SetNillableLookupKey sets the "lookup_key" field if the given value is not nil.
func (_u *DictionaryIndexEntryUpdate) SetNillableLookupKey(v *string) *DictionaryIndexEntryUpdate {
	if v != nil {
		_u.SetLookupKey(*v)
	}
	return _u
}

// SetLookupKeyLower sets the "lookup_key_lower" field.
func (_u *DictionaryIndexEntryUpdate) SetLookupKeyLower(v string) *DictionaryIndexEntryUpdate {
	_u.mutation.SetLookupKeyLower(v)
	return _u
}

// SetNillableLookupKeyLower sets the "lookup_key_lower" field if the given value is not nil.
func (_u *DictionaryIndexEntryUpdate) SetNillableLookupKeyLower(v *string) *DictionaryIndexEntryUpdate {
	if v != nil {
		_u.SetLookupKeyLower(*v)
	}
	return _u
}

// SetRecordStartOffset sets the "record_start_offset" field.
func (_u *DictionaryIndexEntryUpdate) SetRecordStartOffset(v int64) *DictionaryIndexEntryUpdate {
	_u.mutation.ResetRecordStartOffset()
	_u.mutation.SetRecordStartOffset(v)
	return _u
}

// SetNillableRecordStartOffset sets the "record_start_offset" field if the given value is not nil.
func (_u *DictionaryIndexEntryUpdate) SetNillableRecordStartOffset(v *int64) *DictionaryIndexEntryUpdate {
	if v != nil {
		_u.SetRecordStartOffset(*v)
	}
	return _u
}

// AddRecordStartOffset adds value to the "record_start_offset" field.
func (_u *DictionaryIndexEntryUpdate) AddRecordStartOffset(v int64) *DictionaryIndexEntryUpdate {
	_u.mutation.AddRecordStartOffset(v)
	return _u
}

// SetRecordEndOffset sets the "record_end_offset" field.
func (_u *DictionaryIndexEntryUpdate) SetRecordEndOffset(v int64) *DictionaryIndexEntryUpdate {
	_u.mutation.ResetRecordEndOffset()
	_u.mutation.SetRecordEndOffset(v)
	return _u
}

// SetNillableRecordEndOffset sets the "record_end_offset" field if the given value is not nil.
func (_u *DictionaryIndexEntryUpdate) SetNillableRecordEndOffset(v *int64) *DictionaryIndexEntryUpdate {
	if v != nil {
		_u.SetRecordEndOffset(*v)
	}
	return _u
}

// AddRecordEndOffset adds value to the "record_end_offset" field.
func (_u *DictionaryIndexEntryUpdate) AddRecordEndOffset(v int64) *DictionaryIndexEntryUpdate {
	_u.mutation.AddRecordEndOffset(v)
	return _u
}

// SetKeyBlockIdx sets the "key_block_idx" field.
func (_u *DictionaryIndexEntryUpdate) SetKeyBlockIdx(v int64) *DictionaryIndexEntryUpdate {
	_u.mutation.ResetKeyBlockIdx()
	_u.mutation.SetKeyBlockIdx(v)
	return _u
}

// SetNillableKeyBlockIdx sets the "key_block_idx" field if the given value is not nil.
func (_u *DictionaryIndexEntryUpdate) SetNillableKeyBlockIdx(v *int64) *DictionaryIndexEntryUpdate {
	if v != nil {
		_u.SetKeyBlockIdx(*v)
	}
	return _u
}

// AddKeyBlockIdx adds value to the "key_block_idx" field.
func (_u *DictionaryIndexEntryUpdate) AddKeyBlockIdx(v int64) *DictionaryIndexEntryUpdate {
	_u.mutation.AddKeyBlockIdx(v)
	return _u
}

// SetIsResource sets the "is_resource" field.
func (_u *DictionaryIndexEntryUpdate) SetIsResource(v bool) *DictionaryIndexEntryUpdate {
	_u.mutation.SetIsResource(v)
	return _u
}

// SetNillableIsResource sets the "is_resource" field if the given value is not nil.
func (_u *DictionaryIndexEntryUpdate) SetNillableIsResource(v *bool) *DictionaryIndexEntryUpdate {
	if v != nil {
		_u.SetIsResource(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *DictionaryIndexEntryUpdate) SetPayload(v string) *DictionaryIndexEntryUpdate {
	_u.mutation.SetPayload(v)
	return _u
}

// SetNillablePayload sets the "payload" field if the given value is not nil.
func (_u *DictionaryIndexEntryUpdate) SetNillablePayload(v *string) *DictionaryIndexEntryUpdate {
	if v != nil {
		_u.SetPayload(*v)
	}
	return _u
}

// Mutation returns the DictionaryIndexEntryMutation object of the builder.
func (_u *DictionaryIndexEntryUpdate) Mutation() *DictionaryIndexEntryMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DictionaryIndexEntryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DictionaryIndexEntryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DictionaryIndexEntryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DictionaryIndexEntryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DictionaryIndexEntryUpdate) check() error {
	if v, ok := _u.mutation.DictionaryName(); ok {
		if err := dictionaryindexentry.DictionaryNameValidator(v); err != nil {
			return &ValidationError{Name: "dictionary_name", err: fmt.Errorf(`ent: validator failed for field "DictionaryIndexEntry.dictionary_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Keyword(); ok {
		if err := dictionaryindexentry.KeywordValidator(v); err != nil {
			return &ValidationError{Name: "keyword", err: fmt.Errorf(`ent: validator failed for field "DictionaryIndexEntry.keyword": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LookupKey(); ok {
		if err := dictionaryindexentry.LookupKeyValidator(v); err != nil {
			return &ValidationError{Name: "lookup_key", err: fmt.Errorf(`ent: validator failed for field "DictionaryIndexEntry.lookup_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LookupKeyLower(); ok {
		if err := dictionaryindexentry.LookupKeyLowerValidator(v); err != nil {
			return &ValidationError{Name: "lookup_key_lower", err: fmt.Errorf(`ent: validator failed for field "DictionaryIndexEntry.lookup_key_lower": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Payload(); ok {
		if err := dictionaryindexentry.PayloadValidator(v); err != nil {
			return &ValidationError{Name: "payload", err: fmt.Errorf(`ent: validator failed for field "DictionaryIndexEntry.payload": %w`, err)}
		}
	}
	return nil
}

func (_u *DictionaryIndexEntryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dictionaryindexentry.Table, dictionaryindexentry.Columns, sqlgraph.NewFieldSpec(dictionaryindexentry.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DictionaryName(); ok {
		_spec.SetField(dictionaryindexentry.FieldDictionaryName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Keyword(); ok {
		_spec.SetField(dictionaryindexentry.FieldKeyword, field.TypeString, value)
	}
	if value, ok := _u.mutation.NormalizedKeyword(); ok {
		_spec.SetField(dictionaryindexentry.FieldNormalizedKeyword, field.TypeString, value)
	}
	if value, ok := _u.mutation.LookupKey(); ok {
		_spec.SetField(dictionaryindexentry.FieldLookupKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.LookupKeyLower(); ok {
		_spec.SetField(dictionaryindexentry.FieldLookupKeyLower, field.TypeString, value)
	}
	if value, ok := _u.mutation.RecordStartOffset(); ok {
		_spec.SetField(dictionaryindexentry.FieldRecordStartOffset, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRecordStartOffset(); ok {
		_spec.AddField(dictionaryindexentry.FieldRecordStartOffset, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RecordEndOffset(); ok {
		_spec.SetField(dictionaryindexentry.FieldRecordEndOffset, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRecordEndOffset(); ok {
		_spec.AddField(dictionaryindexentry.FieldRecordEndOffset, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.KeyBlockIdx(); ok {
		_spec.SetField(dictionaryindexentry.FieldKeyBlockIdx, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedKeyBlockIdx(); ok {
		_spec.AddField(dictionaryindexentry.FieldKeyBlockIdx, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.IsResource(); ok {
		_spec.SetField(dictionaryindexentry.FieldIsResource, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(dictionaryindexentry.FieldPayload, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dictionaryindexentry.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DictionaryIndexEntryUpdateOne is the builder for updating a single DictionaryIndexEntry entity.
type DictionaryIndexEntryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DictionaryIndexEntryMutation
}

// SetDictionaryName sets the "dictionary_name" field.
func (_u *DictionaryIndexEntryUpdateOne) SetDictionaryName(v string) *DictionaryIndexEntryUpdateOne {
	_u.mutation.SetDictionaryName(v)
	return _u
}

// SetNillableDictionaryName sets the "dictionary_name" field if the given value is not nil.
func (_u *DictionaryIndexEntryUpdateOne) SetNillableDictionaryName(v *string) *DictionaryIndexEntryUpdateOne {
	if v != nil {
		_u.SetDictionaryName(*v)
	}
	return _u
}

// SetKeyword sets the "keyword" field.
func (_u *DictionaryIndexEntryUpdateOne) SetKeyword(v string) *DictionaryIndexEntryUpdateOne {
	_u.mutation.SetKeyword(v)
	return _u
}

// SetNillableKeyword sets the "keyword" field if the given value is not nil.
func (_u *DictionaryIndexEntryUpdateOne) SetNillableKeyword(v *string) *DictionaryIndexEntryUpdateOne {
	if v != nil {
		_u.SetKeyword(*v)
	}
	return _u
}

// SetNormalizedKeyword sets the "normalized_keyword" field.
func (_u *DictionaryIndexEntryUpdateOne) SetNormalizedKeyword(v string) *DictionaryIndexEntryUpdateOne {
	_u.mutation.SetNormalizedKeyword(v)
	return _u
}

// SetNillableNormalizedKeyword sets the "normalized_keyword" field if the given value is not nil.
func (_u *DictionaryIndexEntryUpdateOne) SetNillableNormalizedKeyword(v *string) *DictionaryIndexEntryUpdateOne {
	if v != nil {
		_u.SetNormalizedKeyword(*v)
	}
	return _u
}

// SetLookupKey sets the "lookup_key" field.
func (_u *DictionaryIndexEntryUpdateOne) SetLookupKey(v string) *DictionaryIndexEntryUpdateOne {
	_u.mutation.SetLookupKey(v)
	return _u
}

// SetNillableLookupKey sets the "lookup_key" field if the given value is not nil.
func (_u *DictionaryIndexEntryUpdateOne) SetNillableLookupKey(v *string) *DictionaryIndexEntryUpdateOne {
	if v != nil {
		_u.SetLookupKey(*v)
	}
	return _u
}

// SetLookupKeyLower sets the "lookup_key_lower" field.
func (_u *DictionaryIndexEntryUpdateOne) SetLookupKeyLower(v string) *DictionaryIndexEntryUpdateOne {
	_u.mutation.SetLookupKeyLower(v)
	return _u
}

// SetNillableLookupKeyLower sets the "lookup_key_lower" field if the given value is not nil.
func (_u *DictionaryIndexEntryUpdateOne) SetNillableLookupKeyLower(v *string) *DictionaryIndexEntryUpdateOne {
	if v != nil {
		_u.SetLookupKeyLower(*v)
	}
	return _u
}

// SetRecordStartOffset sets the "record_start_offset" field.
func (_u *DictionaryIndexEntryUpdateOne) SetRecordStartOffset(v int64) *DictionaryIndexEntryUpdateOne {
	_u.mutation.ResetRecordStartOffset()
	_u.mutation.SetRecordStartOffset(v)
	return _u
}

// SetNillableRecordStartOffset sets the "record_start_offset" field if the given value is not nil.
func (_u *DictionaryIndexEntryUpdateOne) SetNillableRecordStartOffset(v *int64) *DictionaryIndexEntryUpdateOne {
	if v != nil {
		_u.SetRecordStartOffset(*v)
	}
	return _u
}

// AddRecordStartOffset adds value to the "record_start_offset" field.
func (_u *DictionaryIndexEntryUpdateOne) AddRecordStartOffset(v int64) *DictionaryIndexEntryUpdateOne {
	_u.mutation.AddRecordStartOffset(v)
	return _u
}

// SetRecordEndOffset sets the "record_end_offset" field.
func (_u *DictionaryIndexEntryUpdateOne) SetRecordEndOffset(v int64) *DictionaryIndexEntryUpdateOne {
	_u.mutation.ResetRecordEndOffset()
	_u.mutation.SetRecordEndOffset(v)
	return _u
}

// SetNillableRecordEndOffset sets the "record_end_offset" field if the given value is not nil.
func (_u *DictionaryIndexEntryUpdateOne) SetNillableRecordEndOffset(v *int64) *DictionaryIndexEntryUpdateOne {
	if v != nil {
		_u.SetRecordEndOffset(*v)
	}
	return _u
}

// AddRecordEndOffset adds value to the "record_end_offset" field.
func (_u *DictionaryIndexEntryUpdateOne) AddRecordEndOffset(v int64) *DictionaryIndexEntryUpdateOne {
	_u.mutation.AddRecordEndOffset(v)
	return _u
}

// SetKeyBlockIdx sets the "key_block_idx" field.
func (_u *DictionaryIndexEntryUpdateOne) SetKeyBlockIdx(v int64) *DictionaryIndexEntryUpdateOne {
	_u.mutation.ResetKeyBlockIdx()
	_u.mutation.SetKeyBlockIdx(v)
	return _u
}

// SetNillableKeyBlockIdx sets the "key_block_idx" field if the given value is not nil.
func (_u *DictionaryIndexEntryUpdateOne) SetNillableKeyBlockIdx(v *int64) *DictionaryIndexEntryUpdateOne {
	if v != nil {
		_u.SetKeyBlockIdx(*v)
	}
	return _u
}

// AddKeyBlockIdx adds value to the "key_block_idx" field.
func (_u *DictionaryIndexEntryUpdateOne) AddKeyBlockIdx(v int64) *DictionaryIndexEntryUpdateOne {
	_u.mutation.AddKeyBlockIdx(v)
	return _u
}

// SetIsResource sets the "is_resource" field.
func (_u *DictionaryIndexEntryUpdateOne) SetIsResource(v bool) *DictionaryIndexEntryUpdateOne {
	_u.mutation.SetIsResource(v)
	return _u
}

// SetNillableIsResource sets the "is_resource" field if the given value is not nil.
func (_u *DictionaryIndexEntryUpdateOne) SetNillableIsResource(v *bool) *DictionaryIndexEntryUpdateOne {
	if v != nil {
		_u.SetIsResource(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *DictionaryIndexEntryUpdateOne) SetPayload(v string) *DictionaryIndexEntryUpdateOne {
	_u.mutation.SetPayload(v)
	return _u
}

// SetNillablePayload sets the "payload" field if the given value is not nil.
func (_u *DictionaryIndexEntryUpdateOne) SetNillablePayload(v *string) *DictionaryIndexEntryUpdateOne {
	if v != nil {
		_u.SetPayload(*v)
	}
	return _u
}

// Mutation returns the DictionaryIndexEntryMutation object of the builder.
func (_u *DictionaryIndexEntryUpdateOne) Mutation() *DictionaryIndexEntryMutation {
	return _u.mutation
}

// Where appends a list predicates to the DictionaryIndexEntryUpdate builder.
func (_u *DictionaryIndexEntryUpdateOne) Where(ps ...predicate.DictionaryIndexEntry) *DictionaryIndexEntryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DictionaryIndexEntryUpdateOne) Select(field string, fields ...string) *DictionaryIndexEntryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DictionaryIndexEntry entity.
func (_u *DictionaryIndexEntryUpdateOne) Save(ctx context.Context) (*DictionaryIndexEntry, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DictionaryIndexEntryUpdateOne) SaveX(ctx context.Context) *DictionaryIndexEntry {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DictionaryIndexEntryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DictionaryIndexEntryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DictionaryIndexEntryUpdateOne) check() error {
	if v, ok := _u.mutation.DictionaryName(); ok {
		if err := dictionaryindexentry.DictionaryNameValidator(v); err != nil {
			return &ValidationError{Name: "dictionary_name", err: fmt.Errorf(`ent: validator failed for field "DictionaryIndexEntry.dictionary_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Keyword(); ok {
		if err := dictionaryindexentry.KeywordValidator(v); err != nil {
			return &ValidationError{Name: "keyword", err: fmt.Errorf(`ent: validator failed for field "DictionaryIndexEntry.keyword": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LookupKey(); ok {
		if err := dictionaryindexentry.LookupKeyValidator(v); err != nil {
			return &ValidationError{Name: "lookup_key", err: fmt.Errorf(`ent: validator failed for field "DictionaryIndexEntry.lookup_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LookupKeyLower(); ok {
		if err := dictionaryindexentry.LookupKeyLowerValidator(v); err != nil {
			return &ValidationError{Name: "lookup_key_lower", err: fmt.Errorf(`ent: validator failed for field "DictionaryIndexEntry.lookup_key_lower": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Payload(); ok {
		if err := dictionaryindexentry.PayloadValidator(v); err != nil {
			return &ValidationError{Name: "payload", err: fmt.Errorf(`ent: validator failed for field "DictionaryIndexEntry.payload": %w`, err)}
		}
	}
	return nil
}

func (_u *DictionaryIndexEntryUpdateOne) sqlSave(ctx context.Context) (_node *DictionaryIndexEntry, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dictionaryindexentry.Table, dictionaryindexentry.Columns, sqlgraph.NewFieldSpec(dictionaryindexentry.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DictionaryIndexEntry.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dictionaryindexentry.FieldID)
		for _, f := range fields {
			if !dictionaryindexentry.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != dictionaryindexentry.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DictionaryName(); ok {
		_spec.SetField(dictionaryindexentry.FieldDictionaryName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Keyword(); ok {
		_spec.SetField(dictionaryindexentry.FieldKeyword, field.TypeString, value)
	}
	if value, ok := _u.mutation.NormalizedKeyword(); ok {
		_spec.SetField(dictionaryindexentry.FieldNormalizedKeyword, field.TypeString, value)
	}
	if value, ok := _u.mutation.LookupKey(); ok {
		_spec.SetField(dictionaryindexentry.FieldLookupKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.LookupKeyLower(); ok {
		_spec.SetField(dictionaryindexentry.FieldLookupKeyLower, field.TypeString, value)
	}
	if value, ok := _u.mutation.RecordStartOffset(); ok {
		_spec.SetField(dictionaryindexentry.FieldRecordStartOffset, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRecordStartOffset(); ok {
		_spec.AddField(dictionaryindexentry.FieldRecordStartOffset, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RecordEndOffset(); ok {
		_spec.SetField(dictionaryindexentry.FieldRecordEndOffset, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRecordEndOffset(); ok {
		_spec.AddField(dictionaryindexentry.FieldRecordEndOffset, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.KeyBlockIdx(); ok {
		_spec.SetField(dictionaryindexentry.FieldKeyBlockIdx, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedKeyBlockIdx(); ok {
		_spec.AddField(dictionaryindexentry.FieldKeyBlockIdx, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.IsResource(); ok {
		_spec.SetField(dictionaryindexentry.FieldIsResource, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(dictionaryindexentry.FieldPayload, field.TypeString, value)
	}
	_node = &DictionaryIndexEntry{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dictionaryindexentry.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
