// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"owl/backend/ent/dictionary"
	"owl/backend/ent/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DictionaryCreate is the builder for creating a Dictionary entity.
type DictionaryCreate struct {
	config
	mutation *DictionaryMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *DictionaryCreate) SetName(v string) *DictionaryCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *DictionaryCreate) SetTitle(v string) *DictionaryCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_c *DictionaryCreate) SetNillableTitle(v *string) *DictionaryCreate {
	if v != nil {
		_c.SetTitle(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *DictionaryCreate) SetDescription(v string) *DictionaryCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *DictionaryCreate) SetNillableDescription(v *string) *DictionaryCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetSlug sets the "slug" field.
func (_c *DictionaryCreate) SetSlug(v string) *DictionaryCreate {
	_c.mutation.SetSlug(v)
	return _c
}

// SetMdxPath sets the "mdx_path" field.
func (_c *DictionaryCreate) SetMdxPath(v string) *DictionaryCreate {
	_c.mutation.SetMdxPath(v)
	return _c
}

// SetMddPathsJSON sets the "mdd_paths_json" field.
func (_c *DictionaryCreate) SetMddPathsJSON(v string) *DictionaryCreate {
	_c.mutation.SetMddPathsJSON(v)
	return _c
}

// SetNillableMddPathsJSON sets the "mdd_paths_json" field if the given value is not nil.
func (_c *DictionaryCreate) SetNillableMddPathsJSON(v *string) *DictionaryCreate {
	if v != nil {
		_c.SetMddPathsJSON(*v)
	}
	return _c
}

// SetEntryCount sets the "entry_count" field.
func (_c *DictionaryCreate) SetEntryCount(v int) *DictionaryCreate {
	_c.mutation.SetEntryCount(v)
	return _c
}

// SetNillableEntryCount sets the "entry_count" field if the given value is not nil.
func (_c *DictionaryCreate) SetNillableEntryCount(v *int) *DictionaryCreate {
	if v != nil {
		_c.SetEntryCount(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *DictionaryCreate) SetEnabled(v bool) *DictionaryCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *DictionaryCreate) SetNillableEnabled(v *bool) *DictionaryCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DictionaryCreate) SetCreatedAt(v time.Time) *DictionaryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DictionaryCreate) SetNillableCreatedAt(v *time.Time) *DictionaryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DictionaryCreate) SetUpdatedAt(v time.Time) *DictionaryCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DictionaryCreate) SetNillableUpdatedAt(v *time.Time) *DictionaryCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_c *DictionaryCreate) SetOwnerID(id int) *DictionaryCreate {
	_c.mutation.SetOwnerID(id)
	return _c
}

// SetOwner sets the "owner" edge to the User entity.
func (_c *DictionaryCreate) SetOwner(v *User) *DictionaryCreate {
	return _c.SetOwnerID(v.ID)
}

// Mutation returns the DictionaryMutation object of the builder.
func (_c *DictionaryCreate) Mutation() *DictionaryMutation {
	return _c.mutation
}

// Save creates the Dictionary in the database.
func (_c *DictionaryCreate) Save(ctx context.Context) (*Dictionary, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DictionaryCreate) SaveX(ctx context.Context) *Dictionary {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DictionaryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DictionaryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DictionaryCreate) defaults() {
	if _, ok := _c.mutation.Title(); !ok {
		v := dictionary.DefaultTitle
		_c.mutation.SetTitle(v)
	}
	if _, ok := _c.mutation.Description(); !ok {
		v := dictionary.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.MddPathsJSON(); !ok {
		v := dictionary.DefaultMddPathsJSON
		_c.mutation.SetMddPathsJSON(v)
	}
	if _, ok := _c.mutation.EntryCount(); !ok {
		v := dictionary.DefaultEntryCount
		_c.mutation.SetEntryCount(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := dictionary.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := dictionary.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := dictionary.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DictionaryCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Dictionary.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := dictionary.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Dictionary.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Dictionary.title"`)}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "Dictionary.description"`)}
	}
	if _, ok := _c.mutation.Slug(); !ok {
		return &ValidationError{Name: "slug", err: errors.New(`ent: missing required field "Dictionary.slug"`)}
	}
	if v, ok := _c.mutation.Slug(); ok {
		if err := dictionary.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Dictionary.slug": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MdxPath(); !ok {
		return &ValidationError{Name: "mdx_path", err: errors.New(`ent: missing required field "Dictionary.mdx_path"`)}
	}
	if v, ok := _c.mutation.MdxPath(); ok {
		if err := dictionary.MdxPathValidator(v); err != nil {
			return &ValidationError{Name: "mdx_path", err: fmt.Errorf(`ent: validator failed for field "Dictionary.mdx_path": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MddPathsJSON(); !ok {
		return &ValidationError{Name: "mdd_paths_json", err: errors.New(`ent: missing required field "Dictionary.mdd_paths_json"`)}
	}
	if _, ok := _c.mutation.EntryCount(); !ok {
		return &ValidationError{Name: "entry_count", err: errors.New(`ent: missing required field "Dictionary.entry_count"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "Dictionary.enabled"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Dictionary.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Dictionary.updated_at"`)}
	}
	if len(_c.mutation.OwnerIDs()) == 0 {
		return &ValidationError{Name: "owner", err: errors.New(`ent: missing required edge "Dictionary.owner"`)}
	}
	return nil
}

func (_c *DictionaryCreate) sqlSave(ctx context.Context) (*Dictionary, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DictionaryCreate) createSpec() (*Dictionary, *sqlgraph.CreateSpec) {
	var (
		_node = &Dictionary{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(dictionary.Table, sqlgraph.NewFieldSpec(dictionary.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(dictionary.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(dictionary.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(dictionary.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Slug(); ok {
		_spec.SetField(dictionary.FieldSlug, field.TypeString, value)
		_node.Slug = value
	}
	if value, ok := _c.mutation.MdxPath(); ok {
		_spec.SetField(dictionary.FieldMdxPath, field.TypeString, value)
		_node.MdxPath = value
	}
	if value, ok := _c.mutation.MddPathsJSON(); ok {
		_spec.SetField(dictionary.FieldMddPathsJSON, field.TypeString, value)
		_node.MddPathsJSON = value
	}
	if value, ok := _c.mutation.EntryCount(); ok {
		_spec.SetField(dictionary.FieldEntryCount, field.TypeInt, value)
		_node.EntryCount = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(dictionary.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(dictionary.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(dictionary.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dictionary.OwnerTable,
			Columns: []string{dictionary.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_dictionaries = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// DictionaryCreateBulk is the builder for creating many Dictionary entities in bulk.
type DictionaryCreateBulk struct {
	config
	err      error
	builders []*DictionaryCreate
}

// Save creates the Dictionary entities in the database.
func (_c *DictionaryCreateBulk) Save(ctx context.Context) ([]*Dictionary, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Dictionary, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DictionaryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DictionaryCreateBulk) SaveX(ctx context.Context) []*Dictionary {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DictionaryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DictionaryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
