// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"owl/backend/ent/dictionaryindexentry"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DictionaryIndexEntryCreate is the builder for creating a DictionaryIndexEntry entity.
type DictionaryIndexEntryCreate struct {
	config
	mutation *DictionaryIndexEntryMutation
	hooks    []Hook
}

// SetDictionaryName sets the "dictionary_name" field.
func (_c *DictionaryIndexEntryCreate) SetDictionaryName(v string) *DictionaryIndexEntryCreate {
	_c.mutation.SetDictionaryName(v)
	return _c
}

// SetKeyword sets the "keyword" field.
func (_c *DictionaryIndexEntryCreate) SetKeyword(v string) *DictionaryIndexEntryCreate {
	_c.mutation.SetKeyword(v)
	return _c
}

// SetNormalizedKeyword sets the "normalized_keyword" field.
func (_c *DictionaryIndexEntryCreate) SetNormalizedKeyword(v string) *DictionaryIndexEntryCreate {
	_c.mutation.SetNormalizedKeyword(v)
	return _c
}

// SetNillableNormalizedKeyword sets the "normalized_keyword" field if the given value is not nil.
func (_c *DictionaryIndexEntryCreate) SetNillableNormalizedKeyword(v *string) *DictionaryIndexEntryCreate {
	if v != nil {
		_c.SetNormalizedKeyword(*v)
	}
	return _c
}

// SetLookupKey sets the "lookup_key" field.
func (_c *DictionaryIndexEntryCreate) SetLookupKey(v string) *DictionaryIndexEntryCreate {
	_c.mutation.SetLookupKey(v)
	return _c
}

// SetLookupKeyLower sets the "lookup_key_lower" field.
func (_c *DictionaryIndexEntryCreate) SetLookupKeyLower(v string) *DictionaryIndexEntryCreate {
	_c.mutation.SetLookupKeyLower(v)
	return _c
}

// SetRecordStartOffset sets the "record_start_offset" field.
func (_c *DictionaryIndexEntryCreate) SetRecordStartOffset(v int64) *DictionaryIndexEntryCreate {
	_c.mutation.SetRecordStartOffset(v)
	return _c
}

// SetRecordEndOffset sets the "record_end_offset" field.
func (_c *DictionaryIndexEntryCreate) SetRecordEndOffset(v int64) *DictionaryIndexEntryCreate {
	_c.mutation.SetRecordEndOffset(v)
	return _c
}

// SetKeyBlockIdx sets the "key_block_idx" field.
func (_c *DictionaryIndexEntryCreate) SetKeyBlockIdx(v int64) *DictionaryIndexEntryCreate {
	_c.mutation.SetKeyBlockIdx(v)
	return _c
}

// SetIsResource sets the "is_resource" field.
func (_c *DictionaryIndexEntryCreate) SetIsResource(v bool) *DictionaryIndexEntryCreate {
	_c.mutation.SetIsResource(v)
	return _c
}

// SetNillableIsResource sets the "is_resource" field if the given value is not nil.
func (_c *DictionaryIndexEntryCreate) SetNillableIsResource(v *bool) *DictionaryIndexEntryCreate {
	if v != nil {
		_c.SetIsResource(*v)
	}
	return _c
}

// SetPayload sets the "payload" field.
func (_c *DictionaryIndexEntryCreate) SetPayload(v string) *DictionaryIndexEntryCreate {
	_c.mutation.SetPayload(v)
	return _c
}

// Mutation returns the DictionaryIndexEntryMutation object of the builder.
func (_c *DictionaryIndexEntryCreate) Mutation() *DictionaryIndexEntryMutation {
	return _c.mutation
}

// Save creates the DictionaryIndexEntry in the database.
func (_c *DictionaryIndexEntryCreate) Save(ctx context.Context) (*DictionaryIndexEntry, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DictionaryIndexEntryCreate) SaveX(ctx context.Context) *DictionaryIndexEntry {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DictionaryIndexEntryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DictionaryIndexEntryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DictionaryIndexEntryCreate) defaults() {
	if _, ok := _c.mutation.NormalizedKeyword(); !ok {
		v := dictionaryindexentry.DefaultNormalizedKeyword
		_c.mutation.SetNormalizedKeyword(v)
	}
	if _, ok := _c.mutation.IsResource(); !ok {
		v := dictionaryindexentry.DefaultIsResource
		_c.mutation.SetIsResource(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DictionaryIndexEntryCreate) check() error {
	if _, ok := _c.mutation.DictionaryName(); !ok {
		return &ValidationError{Name: "dictionary_name", err: errors.New(`ent: missing required field "DictionaryIndexEntry.dictionary_name"`)}
	}
	if v, ok := _c.mutation.DictionaryName(); ok {
		if err := dictionaryindexentry.DictionaryNameValidator(v); err != nil {
			return &ValidationError{Name: "dictionary_name", err: fmt.Errorf(`ent: validator failed for field "DictionaryIndexEntry.dictionary_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Keyword(); !ok {
		return &ValidationError{Name: "keyword", err: errors.New(`ent: missing required field "DictionaryIndexEntry.keyword"`)}
	}
	if v, ok := _c.mutation.Keyword(); ok {
		if err := dictionaryindexentry.KeywordValidator(v); err != nil {
			return &ValidationError{Name: "keyword", err: fmt.Errorf(`ent: validator failed for field "DictionaryIndexEntry.keyword": %w`, err)}
		}
	}
	if _, ok := _c.mutation.NormalizedKeyword(); !ok {
		return &ValidationError{Name: "normalized_keyword", err: errors.New(`ent: missing required field "DictionaryIndexEntry.normalized_keyword"`)}
	}
	if _, ok := _c.mutation.LookupKey(); !ok {
		return &ValidationError{Name: "lookup_key", err: errors.New(`ent: missing required field "DictionaryIndexEntry.lookup_key"`)}
	}
	if v, ok := _c.mutation.LookupKey(); ok {
		if err := dictionaryindexentry.LookupKeyValidator(v); err != nil {
			return &ValidationError{Name: "lookup_key", err: fmt.Errorf(`ent: validator failed for field "DictionaryIndexEntry.lookup_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LookupKeyLower(); !ok {
		return &ValidationError{Name: "lookup_key_lower", err: errors.New(`ent: missing required field "DictionaryIndexEntry.lookup_key_lower"`)}
	}
	if v, ok := _c.mutation.LookupKeyLower(); ok {
		if err := dictionaryindexentry.LookupKeyLowerValidator(v); err != nil {
			return &ValidationError{Name: "lookup_key_lower", err: fmt.Errorf(`ent: validator failed for field "DictionaryIndexEntry.lookup_key_lower": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RecordStartOffset(); !ok {
		return &ValidationError{Name: "record_start_offset", err: errors.New(`ent: missing required field "DictionaryIndexEntry.record_start_offset"`)}
	}
	if _, ok := _c.mutation.RecordEndOffset(); !ok {
		return &ValidationError{Name: "record_end_offset", err: errors.New(`ent: missing required field "DictionaryIndexEntry.record_end_offset"`)}
	}
	if _, ok := _c.mutation.KeyBlockIdx(); !ok {
		return &ValidationError{Name: "key_block_idx", err: errors.New(`ent: missing required field "DictionaryIndexEntry.key_block_idx"`)}
	}
	if _, ok := _c.mutation.IsResource(); !ok {
		return &ValidationError{Name: "is_resource", err: errors.New(`ent: missing required field "DictionaryIndexEntry.is_resource"`)}
	}
	if _, ok := _c.mutation.Payload(); !ok {
		return &ValidationError{Name: "payload", err: errors.New(`ent: missing required field "DictionaryIndexEntry.payload"`)}
	}
	if v, ok := _c.mutation.Payload(); ok {
		if err := dictionaryindexentry.PayloadValidator(v); err != nil {
			return &ValidationError{Name: "payload", err: fmt.Errorf(`ent: validator failed for field "DictionaryIndexEntry.payload": %w`, err)}
		}
	}
	return nil
}

func (_c *DictionaryIndexEntryCreate) sqlSave(ctx context.Context) (*DictionaryIndexEntry, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DictionaryIndexEntryCreate) createSpec() (*DictionaryIndexEntry, *sqlgraph.CreateSpec) {
	var (
		_node = &DictionaryIndexEntry{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(dictionaryindexentry.Table, sqlgraph.NewFieldSpec(dictionaryindexentry.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.DictionaryName(); ok {
		_spec.SetField(dictionaryindexentry.FieldDictionaryName, field.TypeString, value)
		_node.DictionaryName = value
	}
	if value, ok := _c.mutation.Keyword(); ok {
		_spec.SetField(dictionaryindexentry.FieldKeyword, field.TypeString, value)
		_node.Keyword = value
	}
	if value, ok := _c.mutation.NormalizedKeyword(); ok {
		_spec.SetField(dictionaryindexentry.FieldNormalizedKeyword, field.TypeString, value)
		_node.NormalizedKeyword = value
	}
	if value, ok := _c.mutation.LookupKey(); ok {
		_spec.SetField(dictionaryindexentry.FieldLookupKey, field.TypeString, value)
		_node.LookupKey = value
	}
	if value, ok := _c.mutation.LookupKeyLower(); ok {
		_spec.SetField(dictionaryindexentry.FieldLookupKeyLower, field.TypeString, value)
		_node.LookupKeyLower = value
	}
	if value, ok := _c.mutation.RecordStartOffset(); ok {
		_spec.SetField(dictionaryindexentry.FieldRecordStartOffset, field.TypeInt64, value)
		_node.RecordStartOffset = value
	}
	if value, ok := _c.mutation.RecordEndOffset(); ok {
		_spec.SetField(dictionaryindexentry.FieldRecordEndOffset, field.TypeInt64, value)
		_node.RecordEndOffset = value
	}
	if value, ok := _c.mutation.KeyBlockIdx(); ok {
		_spec.SetField(dictionaryindexentry.FieldKeyBlockIdx, field.TypeInt64, value)
		_node.KeyBlockIdx = value
	}
	if value, ok := _c.mutation.IsResource(); ok {
		_spec.SetField(dictionaryindexentry.FieldIsResource, field.TypeBool, value)
		_node.IsResource = value
	}
	if value, ok := _c.mutation.Payload(); ok {
		_spec.SetField(dictionaryindexentry.FieldPayload, field.TypeString, value)
		_node.Payload = value
	}
	return _node, _spec
}

// DictionaryIndexEntryCreateBulk is the builder for creating many DictionaryIndexEntry entities in bulk.
type DictionaryIndexEntryCreateBulk struct {
	config
	err      error
	builders []*DictionaryIndexEntryCreate
}

// Save creates the DictionaryIndexEntry entities in the database.
func (_c *DictionaryIndexEntryCreateBulk) Save(ctx context.Context) ([]*DictionaryIndexEntry, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DictionaryIndexEntry, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DictionaryIndexEntryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DictionaryIndexEntryCreateBulk) SaveX(ctx context.Context) []*DictionaryIndexEntry {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DictionaryIndexEntryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DictionaryIndexEntryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
