// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"owl/backend/ent/dictionary"
	"owl/backend/ent/predicate"
	"owl/backend/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DictionaryUpdate is the builder for updating Dictionary entities.
type DictionaryUpdate struct {
	config
	hooks    []Hook
	mutation *DictionaryMutation
}

// Where appends a list predicates to the DictionaryUpdate builder.
func (_u *DictionaryUpdate) Where(ps ...predicate.Dictionary) *DictionaryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *DictionaryUpdate) SetName(v string) *DictionaryUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DictionaryUpdate) SetNillableName(v *string) *DictionaryUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *DictionaryUpdate) SetTitle(v string) *DictionaryUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *DictionaryUpdate) SetNillableTitle(v *string) *DictionaryUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *DictionaryUpdate) SetDescription(v string) *DictionaryUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *DictionaryUpdate) SetNillableDescription(v *string) *DictionaryUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetSlug sets the "slug" field.
func (_u *DictionaryUpdate) SetSlug(v string) *DictionaryUpdate {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *DictionaryUpdate) SetNillableSlug(v *string) *DictionaryUpdate {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetMdxPath sets the "mdx_path" field.
func (_u *DictionaryUpdate) SetMdxPath(v string) *DictionaryUpdate {
	_u.mutation.SetMdxPath(v)
	return _u
}

// SetNillableMdxPath sets the "mdx_path" field if the given value is not nil.
func (_u *DictionaryUpdate) SetNillableMdxPath(v *string) *DictionaryUpdate {
	if v != nil {
		_u.SetMdxPath(*v)
	}
	return _u
}

// SetMddPathsJSON sets the "mdd_paths_json" field.
func (_u *DictionaryUpdate) SetMddPathsJSON(v string) *DictionaryUpdate {
	_u.mutation.SetMddPathsJSON(v)
	return _u
}

// SetNillableMddPathsJSON sets the "mdd_paths_json" field if the given value is not nil.
func (_u *DictionaryUpdate) SetNillableMddPathsJSON(v *string) *DictionaryUpdate {
	if v != nil {
		_u.SetMddPathsJSON(*v)
	}
	return _u
}

// SetEntryCount sets the "entry_count" field.
func (_u *DictionaryUpdate) SetEntryCount(v int) *DictionaryUpdate {
	_u.mutation.ResetEntryCount()
	_u.mutation.SetEntryCount(v)
	return _u
}

// SetNillableEntryCount sets the "entry_count" field if the given value is not nil.
func (_u *DictionaryUpdate) SetNillableEntryCount(v *int) *DictionaryUpdate {
	if v != nil {
		_u.SetEntryCount(*v)
	}
	return _u
}

// AddEntryCount adds value to the "entry_count" field.
func (_u *DictionaryUpdate) AddEntryCount(v int) *DictionaryUpdate {
	_u.mutation.AddEntryCount(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *DictionaryUpdate) SetEnabled(v bool) *DictionaryUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *DictionaryUpdate) SetNillableEnabled(v *bool) *DictionaryUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetPublic sets the "public" field.
func (_u *DictionaryUpdate) SetPublic(v bool) *DictionaryUpdate {
	_u.mutation.SetPublic(v)
	return _u
}

// SetNillablePublic sets the "public" field if the given value is not nil.
func (_u *DictionaryUpdate) SetNillablePublic(v *bool) *DictionaryUpdate {
	if v != nil {
		_u.SetPublic(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *DictionaryUpdate) SetCreatedAt(v time.Time) *DictionaryUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *DictionaryUpdate) SetNillableCreatedAt(v *time.Time) *DictionaryUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DictionaryUpdate) SetUpdatedAt(v time.Time) *DictionaryUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_u *DictionaryUpdate) SetOwnerID(id int) *DictionaryUpdate {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *DictionaryUpdate) SetOwner(v *User) *DictionaryUpdate {
	return _u.SetOwnerID(v.ID)
}

// Mutation returns the DictionaryMutation object of the builder.
func (_u *DictionaryUpdate) Mutation() *DictionaryMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *DictionaryUpdate) ClearOwner() *DictionaryUpdate {
	_u.mutation.ClearOwner()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DictionaryUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DictionaryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DictionaryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DictionaryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DictionaryUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := dictionary.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DictionaryUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := dictionary.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Dictionary.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Slug(); ok {
		if err := dictionary.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Dictionary.slug": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MdxPath(); ok {
		if err := dictionary.MdxPathValidator(v); err != nil {
			return &ValidationError{Name: "mdx_path", err: fmt.Errorf(`ent: validator failed for field "Dictionary.mdx_path": %w`, err)}
		}
	}
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Dictionary.owner"`)
	}
	return nil
}

func (_u *DictionaryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dictionary.Table, dictionary.Columns, sqlgraph.NewFieldSpec(dictionary.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(dictionary.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(dictionary.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(dictionary.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(dictionary.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.MdxPath(); ok {
		_spec.SetField(dictionary.FieldMdxPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.MddPathsJSON(); ok {
		_spec.SetField(dictionary.FieldMddPathsJSON, field.TypeString, value)
	}
	if value, ok := _u.mutation.EntryCount(); ok {
		_spec.SetField(dictionary.FieldEntryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEntryCount(); ok {
		_spec.AddField(dictionary.FieldEntryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(dictionary.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Public(); ok {
		_spec.SetField(dictionary.FieldPublic, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(dictionary.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(dictionary.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dictionary.OwnerTable,
			Columns: []string{dictionary.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dictionary.OwnerTable,
			Columns: []string{dictionary.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dictionary.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DictionaryUpdateOne is the builder for updating a single Dictionary entity.
type DictionaryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DictionaryMutation
}

// SetName sets the "name" field.
func (_u *DictionaryUpdateOne) SetName(v string) *DictionaryUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DictionaryUpdateOne) SetNillableName(v *string) *DictionaryUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *DictionaryUpdateOne) SetTitle(v string) *DictionaryUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *DictionaryUpdateOne) SetNillableTitle(v *string) *DictionaryUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *DictionaryUpdateOne) SetDescription(v string) *DictionaryUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *DictionaryUpdateOne) SetNillableDescription(v *string) *DictionaryUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetSlug sets the "slug" field.
func (_u *DictionaryUpdateOne) SetSlug(v string) *DictionaryUpdateOne {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *DictionaryUpdateOne) SetNillableSlug(v *string) *DictionaryUpdateOne {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetMdxPath sets the "mdx_path" field.
func (_u *DictionaryUpdateOne) SetMdxPath(v string) *DictionaryUpdateOne {
	_u.mutation.SetMdxPath(v)
	return _u
}

// SetNillableMdxPath sets the "mdx_path" field if the given value is not nil.
func (_u *DictionaryUpdateOne) SetNillableMdxPath(v *string) *DictionaryUpdateOne {
	if v != nil {
		_u.SetMdxPath(*v)
	}
	return _u
}

// SetMddPathsJSON sets the "mdd_paths_json" field.
func (_u *DictionaryUpdateOne) SetMddPathsJSON(v string) *DictionaryUpdateOne {
	_u.mutation.SetMddPathsJSON(v)
	return _u
}

// SetNillableMddPathsJSON sets the "mdd_paths_json" field if the given value is not nil.
func (_u *DictionaryUpdateOne) SetNillableMddPathsJSON(v *string) *DictionaryUpdateOne {
	if v != nil {
		_u.SetMddPathsJSON(*v)
	}
	return _u
}

// SetEntryCount sets the "entry_count" field.
func (_u *DictionaryUpdateOne) SetEntryCount(v int) *DictionaryUpdateOne {
	_u.mutation.ResetEntryCount()
	_u.mutation.SetEntryCount(v)
	return _u
}

// SetNillableEntryCount sets the "entry_count" field if the given value is not nil.
func (_u *DictionaryUpdateOne) SetNillableEntryCount(v *int) *DictionaryUpdateOne {
	if v != nil {
		_u.SetEntryCount(*v)
	}
	return _u
}

// AddEntryCount adds value to the "entry_count" field.
func (_u *DictionaryUpdateOne) AddEntryCount(v int) *DictionaryUpdateOne {
	_u.mutation.AddEntryCount(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *DictionaryUpdateOne) SetEnabled(v bool) *DictionaryUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *DictionaryUpdateOne) SetNillableEnabled(v *bool) *DictionaryUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetPublic sets the "public" field.
func (_u *DictionaryUpdateOne) SetPublic(v bool) *DictionaryUpdateOne {
	_u.mutation.SetPublic(v)
	return _u
}

// SetNillablePublic sets the "public" field if the given value is not nil.
func (_u *DictionaryUpdateOne) SetNillablePublic(v *bool) *DictionaryUpdateOne {
	if v != nil {
		_u.SetPublic(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *DictionaryUpdateOne) SetCreatedAt(v time.Time) *DictionaryUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *DictionaryUpdateOne) SetNillableCreatedAt(v *time.Time) *DictionaryUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DictionaryUpdateOne) SetUpdatedAt(v time.Time) *DictionaryUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_u *DictionaryUpdateOne) SetOwnerID(id int) *DictionaryUpdateOne {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *DictionaryUpdateOne) SetOwner(v *User) *DictionaryUpdateOne {
	return _u.SetOwnerID(v.ID)
}

// Mutation returns the DictionaryMutation object of the builder.
func (_u *DictionaryUpdateOne) Mutation() *DictionaryMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *DictionaryUpdateOne) ClearOwner() *DictionaryUpdateOne {
	_u.mutation.ClearOwner()
	return _u
}

// Where appends a list predicates to the DictionaryUpdate builder.
func (_u *DictionaryUpdateOne) Where(ps ...predicate.Dictionary) *DictionaryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DictionaryUpdateOne) Select(field string, fields ...string) *DictionaryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Dictionary entity.
func (_u *DictionaryUpdateOne) Save(ctx context.Context) (*Dictionary, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DictionaryUpdateOne) SaveX(ctx context.Context) *Dictionary {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DictionaryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DictionaryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DictionaryUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := dictionary.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DictionaryUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := dictionary.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Dictionary.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Slug(); ok {
		if err := dictionary.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Dictionary.slug": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MdxPath(); ok {
		if err := dictionary.MdxPathValidator(v); err != nil {
			return &ValidationError{Name: "mdx_path", err: fmt.Errorf(`ent: validator failed for field "Dictionary.mdx_path": %w`, err)}
		}
	}
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Dictionary.owner"`)
	}
	return nil
}

func (_u *DictionaryUpdateOne) sqlSave(ctx context.Context) (_node *Dictionary, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dictionary.Table, dictionary.Columns, sqlgraph.NewFieldSpec(dictionary.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Dictionary.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dictionary.FieldID)
		for _, f := range fields {
			if !dictionary.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != dictionary.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(dictionary.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(dictionary.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(dictionary.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(dictionary.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.MdxPath(); ok {
		_spec.SetField(dictionary.FieldMdxPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.MddPathsJSON(); ok {
		_spec.SetField(dictionary.FieldMddPathsJSON, field.TypeString, value)
	}
	if value, ok := _u.mutation.EntryCount(); ok {
		_spec.SetField(dictionary.FieldEntryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEntryCount(); ok {
		_spec.AddField(dictionary.FieldEntryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(dictionary.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Public(); ok {
		_spec.SetField(dictionary.FieldPublic, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(dictionary.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(dictionary.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dictionary.OwnerTable,
			Columns: []string{dictionary.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dictionary.OwnerTable,
			Columns: []string{dictionary.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Dictionary{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dictionary.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
