// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"owl/backend/ent/dictionaryindexmanifest"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// DictionaryIndexManifest is the model entity for the DictionaryIndexManifest schema.
type DictionaryIndexManifest struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// DictionaryName holds the value of the "dictionary_name" field.
	DictionaryName string `json:"dictionary_name,omitempty"`
	// SourcePath holds the value of the "source_path" field.
	SourcePath string `json:"source_path,omitempty"`
	// Fingerprint holds the value of the "fingerprint" field.
	Fingerprint string `json:"fingerprint,omitempty"`
	// SchemaVersion holds the value of the "schema_version" field.
	SchemaVersion string `json:"schema_version,omitempty"`
	// BuiltAt holds the value of the "built_at" field.
	BuiltAt time.Time `json:"built_at,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt    *time.Time `json:"expires_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DictionaryIndexManifest) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case dictionaryindexmanifest.FieldID:
			values[i] = new(sql.NullInt64)
		case dictionaryindexmanifest.FieldDictionaryName, dictionaryindexmanifest.FieldSourcePath, dictionaryindexmanifest.FieldFingerprint, dictionaryindexmanifest.FieldSchemaVersion:
			values[i] = new(sql.NullString)
		case dictionaryindexmanifest.FieldBuiltAt, dictionaryindexmanifest.FieldExpiresAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DictionaryIndexManifest fields.
func (_m *DictionaryIndexManifest) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case dictionaryindexmanifest.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case dictionaryindexmanifest.FieldDictionaryName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field dictionary_name", values[i])
			} else if value.Valid {
				_m.DictionaryName = value.String
			}
		case dictionaryindexmanifest.FieldSourcePath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_path", values[i])
			} else if value.Valid {
				_m.SourcePath = value.String
			}
		case dictionaryindexmanifest.FieldFingerprint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field fingerprint", values[i])
			} else if value.Valid {
				_m.Fingerprint = value.String
			}
		case dictionaryindexmanifest.FieldSchemaVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field schema_version", values[i])
			} else if value.Valid {
				_m.SchemaVersion = value.String
			}
		case dictionaryindexmanifest.FieldBuiltAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field built_at", values[i])
			} else if value.Valid {
				_m.BuiltAt = value.Time
			}
		case dictionaryindexmanifest.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = new(time.Time)
				*_m.ExpiresAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DictionaryIndexManifest.
// This includes values selected through modifiers, order, etc.
func (_m *DictionaryIndexManifest) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this DictionaryIndexManifest.
// Note that you need to call DictionaryIndexManifest.Unwrap() before calling this method if this DictionaryIndexManifest
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DictionaryIndexManifest) Update() *DictionaryIndexManifestUpdateOne {
	return NewDictionaryIndexManifestClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DictionaryIndexManifest entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DictionaryIndexManifest) Unwrap() *DictionaryIndexManifest {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DictionaryIndexManifest is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DictionaryIndexManifest) String() string {
	var builder strings.Builder
	builder.WriteString("DictionaryIndexManifest(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("dictionary_name=")
	builder.WriteString(_m.DictionaryName)
	builder.WriteString(", ")
	builder.WriteString("source_path=")
	builder.WriteString(_m.SourcePath)
	builder.WriteString(", ")
	builder.WriteString("fingerprint=")
	builder.WriteString(_m.Fingerprint)
	builder.WriteString(", ")
	builder.WriteString("schema_version=")
	builder.WriteString(_m.SchemaVersion)
	builder.WriteString(", ")
	builder.WriteString("built_at=")
	builder.WriteString(_m.BuiltAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.ExpiresAt; v != nil {
		builder.WriteString("expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// DictionaryIndexManifests is a parsable slice of DictionaryIndexManifest.
type DictionaryIndexManifests []*DictionaryIndexManifest
