// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"owl/backend/ent/dictionaryindexentry"
	"owl/backend/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DictionaryIndexEntryDelete is the builder for deleting a DictionaryIndexEntry entity.
type DictionaryIndexEntryDelete struct {
	config
	hooks    []Hook
	mutation *DictionaryIndexEntryMutation
}

// Where appends a list predicates to the DictionaryIndexEntryDelete builder.
func (_d *DictionaryIndexEntryDelete) Where(ps ...predicate.DictionaryIndexEntry) *DictionaryIndexEntryDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *DictionaryIndexEntryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DictionaryIndexEntryDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *DictionaryIndexEntryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(dictionaryindexentry.Table, sqlgraph.NewFieldSpec(dictionaryindexentry.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// DictionaryIndexEntryDeleteOne is the builder for deleting a single DictionaryIndexEntry entity.
type DictionaryIndexEntryDeleteOne struct {
	_d *DictionaryIndexEntryDelete
}

// Where appends a list predicates to the DictionaryIndexEntryDelete builder.
func (_d *DictionaryIndexEntryDeleteOne) Where(ps ...predicate.DictionaryIndexEntry) *DictionaryIndexEntryDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *DictionaryIndexEntryDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{dictionaryindexentry.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DictionaryIndexEntryDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
