// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"owl/backend/ent/dictionaryindexmanifest"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DictionaryIndexManifestCreate is the builder for creating a DictionaryIndexManifest entity.
type DictionaryIndexManifestCreate struct {
	config
	mutation *DictionaryIndexManifestMutation
	hooks    []Hook
}

// SetDictionaryName sets the "dictionary_name" field.
func (_c *DictionaryIndexManifestCreate) SetDictionaryName(v string) *DictionaryIndexManifestCreate {
	_c.mutation.SetDictionaryName(v)
	return _c
}

// SetSourcePath sets the "source_path" field.
func (_c *DictionaryIndexManifestCreate) SetSourcePath(v string) *DictionaryIndexManifestCreate {
	_c.mutation.SetSourcePath(v)
	return _c
}

// SetNillableSourcePath sets the "source_path" field if the given value is not nil.
func (_c *DictionaryIndexManifestCreate) SetNillableSourcePath(v *string) *DictionaryIndexManifestCreate {
	if v != nil {
		_c.SetSourcePath(*v)
	}
	return _c
}

// SetFingerprint sets the "fingerprint" field.
func (_c *DictionaryIndexManifestCreate) SetFingerprint(v string) *DictionaryIndexManifestCreate {
	_c.mutation.SetFingerprint(v)
	return _c
}

// SetNillableFingerprint sets the "fingerprint" field if the given value is not nil.
func (_c *DictionaryIndexManifestCreate) SetNillableFingerprint(v *string) *DictionaryIndexManifestCreate {
	if v != nil {
		_c.SetFingerprint(*v)
	}
	return _c
}

// SetSchemaVersion sets the "schema_version" field.
func (_c *DictionaryIndexManifestCreate) SetSchemaVersion(v string) *DictionaryIndexManifestCreate {
	_c.mutation.SetSchemaVersion(v)
	return _c
}

// SetNillableSchemaVersion sets the "schema_version" field if the given value is not nil.
func (_c *DictionaryIndexManifestCreate) SetNillableSchemaVersion(v *string) *DictionaryIndexManifestCreate {
	if v != nil {
		_c.SetSchemaVersion(*v)
	}
	return _c
}

// SetBuiltAt sets the "built_at" field.
func (_c *DictionaryIndexManifestCreate) SetBuiltAt(v time.Time) *DictionaryIndexManifestCreate {
	_c.mutation.SetBuiltAt(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *DictionaryIndexManifestCreate) SetExpiresAt(v time.Time) *DictionaryIndexManifestCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *DictionaryIndexManifestCreate) SetNillableExpiresAt(v *time.Time) *DictionaryIndexManifestCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// Mutation returns the DictionaryIndexManifestMutation object of the builder.
func (_c *DictionaryIndexManifestCreate) Mutation() *DictionaryIndexManifestMutation {
	return _c.mutation
}

// Save creates the DictionaryIndexManifest in the database.
func (_c *DictionaryIndexManifestCreate) Save(ctx context.Context) (*DictionaryIndexManifest, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DictionaryIndexManifestCreate) SaveX(ctx context.Context) *DictionaryIndexManifest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DictionaryIndexManifestCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DictionaryIndexManifestCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DictionaryIndexManifestCreate) defaults() {
	if _, ok := _c.mutation.SourcePath(); !ok {
		v := dictionaryindexmanifest.DefaultSourcePath
		_c.mutation.SetSourcePath(v)
	}
	if _, ok := _c.mutation.Fingerprint(); !ok {
		v := dictionaryindexmanifest.DefaultFingerprint
		_c.mutation.SetFingerprint(v)
	}
	if _, ok := _c.mutation.SchemaVersion(); !ok {
		v := dictionaryindexmanifest.DefaultSchemaVersion
		_c.mutation.SetSchemaVersion(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DictionaryIndexManifestCreate) check() error {
	if _, ok := _c.mutation.DictionaryName(); !ok {
		return &ValidationError{Name: "dictionary_name", err: errors.New(`ent: missing required field "DictionaryIndexManifest.dictionary_name"`)}
	}
	if v, ok := _c.mutation.DictionaryName(); ok {
		if err := dictionaryindexmanifest.DictionaryNameValidator(v); err != nil {
			return &ValidationError{Name: "dictionary_name", err: fmt.Errorf(`ent: validator failed for field "DictionaryIndexManifest.dictionary_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SourcePath(); !ok {
		return &ValidationError{Name: "source_path", err: errors.New(`ent: missing required field "DictionaryIndexManifest.source_path"`)}
	}
	if _, ok := _c.mutation.Fingerprint(); !ok {
		return &ValidationError{Name: "fingerprint", err: errors.New(`ent: missing required field "DictionaryIndexManifest.fingerprint"`)}
	}
	if _, ok := _c.mutation.SchemaVersion(); !ok {
		return &ValidationError{Name: "schema_version", err: errors.New(`ent: missing required field "DictionaryIndexManifest.schema_version"`)}
	}
	if _, ok := _c.mutation.BuiltAt(); !ok {
		return &ValidationError{Name: "built_at", err: errors.New(`ent: missing required field "DictionaryIndexManifest.built_at"`)}
	}
	return nil
}

func (_c *DictionaryIndexManifestCreate) sqlSave(ctx context.Context) (*DictionaryIndexManifest, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DictionaryIndexManifestCreate) createSpec() (*DictionaryIndexManifest, *sqlgraph.CreateSpec) {
	var (
		_node = &DictionaryIndexManifest{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(dictionaryindexmanifest.Table, sqlgraph.NewFieldSpec(dictionaryindexmanifest.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.DictionaryName(); ok {
		_spec.SetField(dictionaryindexmanifest.FieldDictionaryName, field.TypeString, value)
		_node.DictionaryName = value
	}
	if value, ok := _c.mutation.SourcePath(); ok {
		_spec.SetField(dictionaryindexmanifest.FieldSourcePath, field.TypeString, value)
		_node.SourcePath = value
	}
	if value, ok := _c.mutation.Fingerprint(); ok {
		_spec.SetField(dictionaryindexmanifest.FieldFingerprint, field.TypeString, value)
		_node.Fingerprint = value
	}
	if value, ok := _c.mutation.SchemaVersion(); ok {
		_spec.SetField(dictionaryindexmanifest.FieldSchemaVersion, field.TypeString, value)
		_node.SchemaVersion = value
	}
	if value, ok := _c.mutation.BuiltAt(); ok {
		_spec.SetField(dictionaryindexmanifest.FieldBuiltAt, field.TypeTime, value)
		_node.BuiltAt = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(dictionaryindexmanifest.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	return _node, _spec
}

// DictionaryIndexManifestCreateBulk is the builder for creating many DictionaryIndexManifest entities in bulk.
type DictionaryIndexManifestCreateBulk struct {
	config
	err      error
	builders []*DictionaryIndexManifestCreate
}

// Save creates the DictionaryIndexManifest entities in the database.
func (_c *DictionaryIndexManifestCreateBulk) Save(ctx context.Context) ([]*DictionaryIndexManifest, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DictionaryIndexManifest, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DictionaryIndexManifestMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DictionaryIndexManifestCreateBulk) SaveX(ctx context.Context) []*DictionaryIndexManifest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DictionaryIndexManifestCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DictionaryIndexManifestCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
