// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"owl/backend/ent/dictionaryindexmanifest"
	"owl/backend/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DictionaryIndexManifestDelete is the builder for deleting a DictionaryIndexManifest entity.
type DictionaryIndexManifestDelete struct {
	config
	hooks    []Hook
	mutation *DictionaryIndexManifestMutation
}

// Where appends a list predicates to the DictionaryIndexManifestDelete builder.
func (_d *DictionaryIndexManifestDelete) Where(ps ...predicate.DictionaryIndexManifest) *DictionaryIndexManifestDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *DictionaryIndexManifestDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DictionaryIndexManifestDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *DictionaryIndexManifestDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(dictionaryindexmanifest.Table, sqlgraph.NewFieldSpec(dictionaryindexmanifest.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// DictionaryIndexManifestDeleteOne is the builder for deleting a single DictionaryIndexManifest entity.
type DictionaryIndexManifestDeleteOne struct {
	_d *DictionaryIndexManifestDelete
}

// Where appends a list predicates to the DictionaryIndexManifestDelete builder.
func (_d *DictionaryIndexManifestDeleteOne) Where(ps ...predicate.DictionaryIndexManifest) *DictionaryIndexManifestDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *DictionaryIndexManifestDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{dictionaryindexmanifest.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DictionaryIndexManifestDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
