// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"owl/backend/ent/font"
	"owl/backend/ent/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FontCreate is the builder for creating a Font entity.
type FontCreate struct {
	config
	mutation *FontMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *FontCreate) SetName(v string) *FontCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetFamily sets the "family" field.
func (_c *FontCreate) SetFamily(v string) *FontCreate {
	_c.mutation.SetFamily(v)
	return _c
}

// SetPath sets the "path" field.
func (_c *FontCreate) SetPath(v string) *FontCreate {
	_c.mutation.SetPath(v)
	return _c
}

// SetMime sets the "mime" field.
func (_c *FontCreate) SetMime(v string) *FontCreate {
	_c.mutation.SetMime(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *FontCreate) SetCreatedAt(v time.Time) *FontCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *FontCreate) SetNillableCreatedAt(v *time.Time) *FontCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *FontCreate) SetUpdatedAt(v time.Time) *FontCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *FontCreate) SetNillableUpdatedAt(v *time.Time) *FontCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// AddSelectedByIDs adds the "selected_by" edge to the User entity by IDs.
func (_c *FontCreate) AddSelectedByIDs(ids ...int) *FontCreate {
	_c.mutation.AddSelectedByIDs(ids...)
	return _c
}

// AddSelectedBy adds the "selected_by" edges to the User entity.
func (_c *FontCreate) AddSelectedBy(v ...*User) *FontCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSelectedByIDs(ids...)
}

// Mutation returns the FontMutation object of the builder.
func (_c *FontCreate) Mutation() *FontMutation {
	return _c.mutation
}

// Save creates the Font in the database.
func (_c *FontCreate) Save(ctx context.Context) (*Font, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *FontCreate) SaveX(ctx context.Context) *Font {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FontCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FontCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *FontCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := font.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := font.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *FontCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Font.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := font.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Font.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Family(); !ok {
		return &ValidationError{Name: "family", err: errors.New(`ent: missing required field "Font.family"`)}
	}
	if v, ok := _c.mutation.Family(); ok {
		if err := font.FamilyValidator(v); err != nil {
			return &ValidationError{Name: "family", err: fmt.Errorf(`ent: validator failed for field "Font.family": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Path(); !ok {
		return &ValidationError{Name: "path", err: errors.New(`ent: missing required field "Font.path"`)}
	}
	if v, ok := _c.mutation.Path(); ok {
		if err := font.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "Font.path": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Mime(); !ok {
		return &ValidationError{Name: "mime", err: errors.New(`ent: missing required field "Font.mime"`)}
	}
	if v, ok := _c.mutation.Mime(); ok {
		if err := font.MimeValidator(v); err != nil {
			return &ValidationError{Name: "mime", err: fmt.Errorf(`ent: validator failed for field "Font.mime": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Font.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Font.updated_at"`)}
	}
	return nil
}

func (_c *FontCreate) sqlSave(ctx context.Context) (*Font, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *FontCreate) createSpec() (*Font, *sqlgraph.CreateSpec) {
	var (
		_node = &Font{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(font.Table, sqlgraph.NewFieldSpec(font.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(font.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Family(); ok {
		_spec.SetField(font.FieldFamily, field.TypeString, value)
		_node.Family = value
	}
	if value, ok := _c.mutation.Path(); ok {
		_spec.SetField(font.FieldPath, field.TypeString, value)
		_node.Path = value
	}
	if value, ok := _c.mutation.Mime(); ok {
		_spec.SetField(font.FieldMime, field.TypeString, value)
		_node.Mime = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(font.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(font.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.SelectedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   font.SelectedByTable,
			Columns: []string{font.SelectedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// FontCreateBulk is the builder for creating many Font entities in bulk.
type FontCreateBulk struct {
	config
	err      error
	builders []*FontCreate
}

// Save creates the Font entities in the database.
func (_c *FontCreateBulk) Save(ctx context.Context) ([]*Font, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Font, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FontMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *FontCreateBulk) SaveX(ctx context.Context) []*Font {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FontCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FontCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
