// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"owl/backend/ent/font"
	"owl/backend/ent/predicate"
	"owl/backend/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FontUpdate is the builder for updating Font entities.
type FontUpdate struct {
	config
	hooks    []Hook
	mutation *FontMutation
}

// Where appends a list predicates to the FontUpdate builder.
func (_u *FontUpdate) Where(ps ...predicate.Font) *FontUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *FontUpdate) SetName(v string) *FontUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *FontUpdate) SetNillableName(v *string) *FontUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetFamily sets the "family" field.
func (_u *FontUpdate) SetFamily(v string) *FontUpdate {
	_u.mutation.SetFamily(v)
	return _u
}

// SetNillableFamily sets the "family" field if the given value is not nil.
func (_u *FontUpdate) SetNillableFamily(v *string) *FontUpdate {
	if v != nil {
		_u.SetFamily(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *FontUpdate) SetPath(v string) *FontUpdate {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *FontUpdate) SetNillablePath(v *string) *FontUpdate {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetMime sets the "mime" field.
func (_u *FontUpdate) SetMime(v string) *FontUpdate {
	_u.mutation.SetMime(v)
	return _u
}

// SetNillableMime sets the "mime" field if the given value is not nil.
func (_u *FontUpdate) SetNillableMime(v *string) *FontUpdate {
	if v != nil {
		_u.SetMime(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *FontUpdate) SetCreatedAt(v time.Time) *FontUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *FontUpdate) SetNillableCreatedAt(v *time.Time) *FontUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FontUpdate) SetUpdatedAt(v time.Time) *FontUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddSelectedByIDs adds the "selected_by" edge to the User entity by IDs.
func (_u *FontUpdate) AddSelectedByIDs(ids ...int) *FontUpdate {
	_u.mutation.AddSelectedByIDs(ids...)
	return _u
}

// AddSelectedBy adds the "selected_by" edges to the User entity.
func (_u *FontUpdate) AddSelectedBy(v ...*User) *FontUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSelectedByIDs(ids...)
}

// Mutation returns the FontMutation object of the builder.
func (_u *FontUpdate) Mutation() *FontMutation {
	return _u.mutation
}

// ClearSelectedBy clears all "selected_by" edges to the User entity.
func (_u *FontUpdate) ClearSelectedBy() *FontUpdate {
	_u.mutation.ClearSelectedBy()
	return _u
}

// RemoveSelectedByIDs removes the "selected_by" edge to User entities by IDs.
func (_u *FontUpdate) RemoveSelectedByIDs(ids ...int) *FontUpdate {
	_u.mutation.RemoveSelectedByIDs(ids...)
	return _u
}

// RemoveSelectedBy removes "selected_by" edges to User entities.
func (_u *FontUpdate) RemoveSelectedBy(v ...*User) *FontUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSelectedByIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FontUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FontUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FontUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FontUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FontUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := font.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FontUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := font.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Font.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Family(); ok {
		if err := font.FamilyValidator(v); err != nil {
			return &ValidationError{Name: "family", err: fmt.Errorf(`ent: validator failed for field "Font.family": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Path(); ok {
		if err := font.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "Font.path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Mime(); ok {
		if err := font.MimeValidator(v); err != nil {
			return &ValidationError{Name: "mime", err: fmt.Errorf(`ent: validator failed for field "Font.mime": %w`, err)}
		}
	}
	return nil
}

func (_u *FontUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(font.Table, font.Columns, sqlgraph.NewFieldSpec(font.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(font.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Family(); ok {
		_spec.SetField(font.FieldFamily, field.TypeString, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(font.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Mime(); ok {
		_spec.SetField(font.FieldMime, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(font.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(font.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.SelectedByCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   font.SelectedByTable,
			Columns: []string{font.SelectedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSelectedByIDs(); len(nodes) > 0 && !_u.mutation.SelectedByCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   font.SelectedByTable,
			Columns: []string{font.SelectedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SelectedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   font.SelectedByTable,
			Columns: []string{font.SelectedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{font.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FontUpdateOne is the builder for updating a single Font entity.
type FontUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FontMutation
}

// SetName sets the "name" field.
func (_u *FontUpdateOne) SetName(v string) *FontUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *FontUpdateOne) SetNillableName(v *string) *FontUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetFamily sets the "family" field.
func (_u *FontUpdateOne) SetFamily(v string) *FontUpdateOne {
	_u.mutation.SetFamily(v)
	return _u
}

// SetNillableFamily sets the "family" field if the given value is not nil.
func (_u *FontUpdateOne) SetNillableFamily(v *string) *FontUpdateOne {
	if v != nil {
		_u.SetFamily(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *FontUpdateOne) SetPath(v string) *FontUpdateOne {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *FontUpdateOne) SetNillablePath(v *string) *FontUpdateOne {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetMime sets the "mime" field.
func (_u *FontUpdateOne) SetMime(v string) *FontUpdateOne {
	_u.mutation.SetMime(v)
	return _u
}

// SetNillableMime sets the "mime" field if the given value is not nil.
func (_u *FontUpdateOne) SetNillableMime(v *string) *FontUpdateOne {
	if v != nil {
		_u.SetMime(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *FontUpdateOne) SetCreatedAt(v time.Time) *FontUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *FontUpdateOne) SetNillableCreatedAt(v *time.Time) *FontUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FontUpdateOne) SetUpdatedAt(v time.Time) *FontUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddSelectedByIDs adds the "selected_by" edge to the User entity by IDs.
func (_u *FontUpdateOne) AddSelectedByIDs(ids ...int) *FontUpdateOne {
	_u.mutation.AddSelectedByIDs(ids...)
	return _u
}

// AddSelectedBy adds the "selected_by" edges to the User entity.
func (_u *FontUpdateOne) AddSelectedBy(v ...*User) *FontUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSelectedByIDs(ids...)
}

// Mutation returns the FontMutation object of the builder.
func (_u *FontUpdateOne) Mutation() *FontMutation {
	return _u.mutation
}

// ClearSelectedBy clears all "selected_by" edges to the User entity.
func (_u *FontUpdateOne) ClearSelectedBy() *FontUpdateOne {
	_u.mutation.ClearSelectedBy()
	return _u
}

// RemoveSelectedByIDs removes the "selected_by" edge to User entities by IDs.
func (_u *FontUpdateOne) RemoveSelectedByIDs(ids ...int) *FontUpdateOne {
	_u.mutation.RemoveSelectedByIDs(ids...)
	return _u
}

// RemoveSelectedBy removes "selected_by" edges to User entities.
func (_u *FontUpdateOne) RemoveSelectedBy(v ...*User) *FontUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSelectedByIDs(ids...)
}

// Where appends a list predicates to the FontUpdate builder.
func (_u *FontUpdateOne) Where(ps ...predicate.Font) *FontUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FontUpdateOne) Select(field string, fields ...string) *FontUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Font entity.
func (_u *FontUpdateOne) Save(ctx context.Context) (*Font, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FontUpdateOne) SaveX(ctx context.Context) *Font {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FontUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FontUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FontUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := font.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FontUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := font.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Font.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Family(); ok {
		if err := font.FamilyValidator(v); err != nil {
			return &ValidationError{Name: "family", err: fmt.Errorf(`ent: validator failed for field "Font.family": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Path(); ok {
		if err := font.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "Font.path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Mime(); ok {
		if err := font.MimeValidator(v); err != nil {
			return &ValidationError{Name: "mime", err: fmt.Errorf(`ent: validator failed for field "Font.mime": %w`, err)}
		}
	}
	return nil
}

func (_u *FontUpdateOne) sqlSave(ctx context.Context) (_node *Font, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(font.Table, font.Columns, sqlgraph.NewFieldSpec(font.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Font.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, font.FieldID)
		for _, f := range fields {
			if !font.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != font.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(font.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Family(); ok {
		_spec.SetField(font.FieldFamily, field.TypeString, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(font.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Mime(); ok {
		_spec.SetField(font.FieldMime, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(font.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(font.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.SelectedByCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   font.SelectedByTable,
			Columns: []string{font.SelectedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSelectedByIDs(); len(nodes) > 0 && !_u.mutation.SelectedByCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   font.SelectedByTable,
			Columns: []string{font.SelectedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SelectedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   font.SelectedByTable,
			Columns: []string{font.SelectedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Font{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{font.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
