// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"owl/backend/ent/font"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Font is the model entity for the Font schema.
type Font struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Family holds the value of the "family" field.
	Family string `json:"family,omitempty"`
	// Path holds the value of the "path" field.
	Path string `json:"path,omitempty"`
	// Mime holds the value of the "mime" field.
	Mime string `json:"mime,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the FontQuery when eager-loading is set.
	Edges        FontEdges `json:"edges"`
	selectValues sql.SelectValues
}

// FontEdges holds the relations/edges for other nodes in the graph.
type FontEdges struct {
	// SelectedBy holds the value of the selected_by edge.
	SelectedBy []*User `json:"selected_by,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SelectedByOrErr returns the SelectedBy value or an error if the edge
// was not loaded in eager-loading.
func (e FontEdges) SelectedByOrErr() ([]*User, error) {
	if e.loadedTypes[0] {
		return e.SelectedBy, nil
	}
	return nil, &NotLoadedError{edge: "selected_by"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Font) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case font.FieldID:
			values[i] = new(sql.NullInt64)
		case font.FieldName, font.FieldFamily, font.FieldPath, font.FieldMime:
			values[i] = new(sql.NullString)
		case font.FieldCreatedAt, font.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Font fields.
func (_m *Font) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case font.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case font.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case font.FieldFamily:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field family", values[i])
			} else if value.Valid {
				_m.Family = value.String
			}
		case font.FieldPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field path", values[i])
			} else if value.Valid {
				_m.Path = value.String
			}
		case font.FieldMime:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mime", values[i])
			} else if value.Valid {
				_m.Mime = value.String
			}
		case font.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case font.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Font.
// This includes values selected through modifiers, order, etc.
func (_m *Font) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySelectedBy queries the "selected_by" edge of the Font entity.
func (_m *Font) QuerySelectedBy() *UserQuery {
	return NewFontClient(_m.config).QuerySelectedBy(_m)
}

// Update returns a builder for updating this Font.
// Note that you need to call Font.Unwrap() before calling this method if this Font
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Font) Update() *FontUpdateOne {
	return NewFontClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Font entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Font) Unwrap() *Font {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Font is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Font) String() string {
	var builder strings.Builder
	builder.WriteString("Font(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("family=")
	builder.WriteString(_m.Family)
	builder.WriteString(", ")
	builder.WriteString("path=")
	builder.WriteString(_m.Path)
	builder.WriteString(", ")
	builder.WriteString("mime=")
	builder.WriteString(_m.Mime)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Fonts is a parsable slice of Font.
type Fonts []*Font
