// Code generated by ent, DO NOT EDIT.

package ent

import (
	"owl/backend/ent/dictionary"
	"owl/backend/ent/font"
	"owl/backend/ent/schema"
	"owl/backend/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	dictionaryFields := schema.Dictionary{}.Fields()
	_ = dictionaryFields
	// dictionaryDescName is the schema descriptor for name field.
	dictionaryDescName := dictionaryFields[0].Descriptor()
	// dictionary.NameValidator is a validator for the "name" field. It is called by the builders before save.
	dictionary.NameValidator = dictionaryDescName.Validators[0].(func(string) error)
	// dictionaryDescTitle is the schema descriptor for title field.
	dictionaryDescTitle := dictionaryFields[1].Descriptor()
	// dictionary.DefaultTitle holds the default value on creation for the title field.
	dictionary.DefaultTitle = dictionaryDescTitle.Default.(string)
	// dictionaryDescDescription is the schema descriptor for description field.
	dictionaryDescDescription := dictionaryFields[2].Descriptor()
	// dictionary.DefaultDescription holds the default value on creation for the description field.
	dictionary.DefaultDescription = dictionaryDescDescription.Default.(string)
	// dictionaryDescSlug is the schema descriptor for slug field.
	dictionaryDescSlug := dictionaryFields[3].Descriptor()
	// dictionary.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	dictionary.SlugValidator = dictionaryDescSlug.Validators[0].(func(string) error)
	// dictionaryDescMdxPath is the schema descriptor for mdx_path field.
	dictionaryDescMdxPath := dictionaryFields[4].Descriptor()
	// dictionary.MdxPathValidator is a validator for the "mdx_path" field. It is called by the builders before save.
	dictionary.MdxPathValidator = dictionaryDescMdxPath.Validators[0].(func(string) error)
	// dictionaryDescMddPathsJSON is the schema descriptor for mdd_paths_json field.
	dictionaryDescMddPathsJSON := dictionaryFields[5].Descriptor()
	// dictionary.DefaultMddPathsJSON holds the default value on creation for the mdd_paths_json field.
	dictionary.DefaultMddPathsJSON = dictionaryDescMddPathsJSON.Default.(string)
	// dictionaryDescEntryCount is the schema descriptor for entry_count field.
	dictionaryDescEntryCount := dictionaryFields[6].Descriptor()
	// dictionary.DefaultEntryCount holds the default value on creation for the entry_count field.
	dictionary.DefaultEntryCount = dictionaryDescEntryCount.Default.(int)
	// dictionaryDescEnabled is the schema descriptor for enabled field.
	dictionaryDescEnabled := dictionaryFields[7].Descriptor()
	// dictionary.DefaultEnabled holds the default value on creation for the enabled field.
	dictionary.DefaultEnabled = dictionaryDescEnabled.Default.(bool)
	// dictionaryDescPublic is the schema descriptor for public field.
	dictionaryDescPublic := dictionaryFields[8].Descriptor()
	// dictionary.DefaultPublic holds the default value on creation for the public field.
	dictionary.DefaultPublic = dictionaryDescPublic.Default.(bool)
	// dictionaryDescCreatedAt is the schema descriptor for created_at field.
	dictionaryDescCreatedAt := dictionaryFields[9].Descriptor()
	// dictionary.DefaultCreatedAt holds the default value on creation for the created_at field.
	dictionary.DefaultCreatedAt = dictionaryDescCreatedAt.Default.(func() time.Time)
	// dictionaryDescUpdatedAt is the schema descriptor for updated_at field.
	dictionaryDescUpdatedAt := dictionaryFields[10].Descriptor()
	// dictionary.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	dictionary.DefaultUpdatedAt = dictionaryDescUpdatedAt.Default.(func() time.Time)
	// dictionary.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	dictionary.UpdateDefaultUpdatedAt = dictionaryDescUpdatedAt.UpdateDefault.(func() time.Time)
	fontFields := schema.Font{}.Fields()
	_ = fontFields
	// fontDescName is the schema descriptor for name field.
	fontDescName := fontFields[0].Descriptor()
	// font.NameValidator is a validator for the "name" field. It is called by the builders before save.
	font.NameValidator = fontDescName.Validators[0].(func(string) error)
	// fontDescFamily is the schema descriptor for family field.
	fontDescFamily := fontFields[1].Descriptor()
	// font.FamilyValidator is a validator for the "family" field. It is called by the builders before save.
	font.FamilyValidator = fontDescFamily.Validators[0].(func(string) error)
	// fontDescPath is the schema descriptor for path field.
	fontDescPath := fontFields[2].Descriptor()
	// font.PathValidator is a validator for the "path" field. It is called by the builders before save.
	font.PathValidator = fontDescPath.Validators[0].(func(string) error)
	// fontDescMime is the schema descriptor for mime field.
	fontDescMime := fontFields[3].Descriptor()
	// font.MimeValidator is a validator for the "mime" field. It is called by the builders before save.
	font.MimeValidator = fontDescMime.Validators[0].(func(string) error)
	// fontDescCreatedAt is the schema descriptor for created_at field.
	fontDescCreatedAt := fontFields[4].Descriptor()
	// font.DefaultCreatedAt holds the default value on creation for the created_at field.
	font.DefaultCreatedAt = fontDescCreatedAt.Default.(func() time.Time)
	// fontDescUpdatedAt is the schema descriptor for updated_at field.
	fontDescUpdatedAt := fontFields[5].Descriptor()
	// font.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	font.DefaultUpdatedAt = fontDescUpdatedAt.Default.(func() time.Time)
	// font.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	font.UpdateDefaultUpdatedAt = fontDescUpdatedAt.UpdateDefault.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[0].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescDisplayName is the schema descriptor for display_name field.
	userDescDisplayName := userFields[1].Descriptor()
	// user.DefaultDisplayName holds the default value on creation for the display_name field.
	user.DefaultDisplayName = userDescDisplayName.Default.(string)
	// userDescAvatarName is the schema descriptor for avatar_name field.
	userDescAvatarName := userFields[2].Descriptor()
	// user.DefaultAvatarName holds the default value on creation for the avatar_name field.
	user.DefaultAvatarName = userDescAvatarName.Default.(string)
	// userDescAvatarPath is the schema descriptor for avatar_path field.
	userDescAvatarPath := userFields[3].Descriptor()
	// user.DefaultAvatarPath holds the default value on creation for the avatar_path field.
	user.DefaultAvatarPath = userDescAvatarPath.Default.(string)
	// userDescAvatarMime is the schema descriptor for avatar_mime field.
	userDescAvatarMime := userFields[4].Descriptor()
	// user.DefaultAvatarMime holds the default value on creation for the avatar_mime field.
	user.DefaultAvatarMime = userDescAvatarMime.Default.(string)
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[5].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = userDescPasswordHash.Validators[0].(func(string) error)
	// userDescIsAdmin is the schema descriptor for is_admin field.
	userDescIsAdmin := userFields[6].Descriptor()
	// user.DefaultIsAdmin holds the default value on creation for the is_admin field.
	user.DefaultIsAdmin = userDescIsAdmin.Default.(bool)
	// userDescLanguage is the schema descriptor for language field.
	userDescLanguage := userFields[7].Descriptor()
	// user.DefaultLanguage holds the default value on creation for the language field.
	user.DefaultLanguage = userDescLanguage.Default.(string)
	// userDescTheme is the schema descriptor for theme field.
	userDescTheme := userFields[8].Descriptor()
	// user.DefaultTheme holds the default value on creation for the theme field.
	user.DefaultTheme = userDescTheme.Default.(string)
	// userDescFontMode is the schema descriptor for font_mode field.
	userDescFontMode := userFields[9].Descriptor()
	// user.DefaultFontMode holds the default value on creation for the font_mode field.
	user.DefaultFontMode = userDescFontMode.Default.(string)
	// userDescMcpTokenHash is the schema descriptor for mcp_token_hash field.
	userDescMcpTokenHash := userFields[10].Descriptor()
	// user.DefaultMcpTokenHash holds the default value on creation for the mcp_token_hash field.
	user.DefaultMcpTokenHash = userDescMcpTokenHash.Default.(string)
	// userDescMcpTokenHint is the schema descriptor for mcp_token_hint field.
	userDescMcpTokenHint := userFields[11].Descriptor()
	// user.DefaultMcpTokenHint holds the default value on creation for the mcp_token_hint field.
	user.DefaultMcpTokenHint = userDescMcpTokenHint.Default.(string)
}
