// Code generated by ent, DO NOT EDIT.

package ent

import (
	"owl/backend/ent/dictionary"
	"owl/backend/ent/schema"
	"owl/backend/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	dictionaryFields := schema.Dictionary{}.Fields()
	_ = dictionaryFields
	// dictionaryDescName is the schema descriptor for name field.
	dictionaryDescName := dictionaryFields[0].Descriptor()
	// dictionary.NameValidator is a validator for the "name" field. It is called by the builders before save.
	dictionary.NameValidator = dictionaryDescName.Validators[0].(func(string) error)
	// dictionaryDescTitle is the schema descriptor for title field.
	dictionaryDescTitle := dictionaryFields[1].Descriptor()
	// dictionary.DefaultTitle holds the default value on creation for the title field.
	dictionary.DefaultTitle = dictionaryDescTitle.Default.(string)
	// dictionaryDescDescription is the schema descriptor for description field.
	dictionaryDescDescription := dictionaryFields[2].Descriptor()
	// dictionary.DefaultDescription holds the default value on creation for the description field.
	dictionary.DefaultDescription = dictionaryDescDescription.Default.(string)
	// dictionaryDescSlug is the schema descriptor for slug field.
	dictionaryDescSlug := dictionaryFields[3].Descriptor()
	// dictionary.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	dictionary.SlugValidator = dictionaryDescSlug.Validators[0].(func(string) error)
	// dictionaryDescMdxPath is the schema descriptor for mdx_path field.
	dictionaryDescMdxPath := dictionaryFields[4].Descriptor()
	// dictionary.MdxPathValidator is a validator for the "mdx_path" field. It is called by the builders before save.
	dictionary.MdxPathValidator = dictionaryDescMdxPath.Validators[0].(func(string) error)
	// dictionaryDescMddPathsJSON is the schema descriptor for mdd_paths_json field.
	dictionaryDescMddPathsJSON := dictionaryFields[5].Descriptor()
	// dictionary.DefaultMddPathsJSON holds the default value on creation for the mdd_paths_json field.
	dictionary.DefaultMddPathsJSON = dictionaryDescMddPathsJSON.Default.(string)
	// dictionaryDescEntryCount is the schema descriptor for entry_count field.
	dictionaryDescEntryCount := dictionaryFields[6].Descriptor()
	// dictionary.DefaultEntryCount holds the default value on creation for the entry_count field.
	dictionary.DefaultEntryCount = dictionaryDescEntryCount.Default.(int)
	// dictionaryDescEnabled is the schema descriptor for enabled field.
	dictionaryDescEnabled := dictionaryFields[7].Descriptor()
	// dictionary.DefaultEnabled holds the default value on creation for the enabled field.
	dictionary.DefaultEnabled = dictionaryDescEnabled.Default.(bool)
	// dictionaryDescCreatedAt is the schema descriptor for created_at field.
	dictionaryDescCreatedAt := dictionaryFields[8].Descriptor()
	// dictionary.DefaultCreatedAt holds the default value on creation for the created_at field.
	dictionary.DefaultCreatedAt = dictionaryDescCreatedAt.Default.(func() time.Time)
	// dictionaryDescUpdatedAt is the schema descriptor for updated_at field.
	dictionaryDescUpdatedAt := dictionaryFields[9].Descriptor()
	// dictionary.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	dictionary.DefaultUpdatedAt = dictionaryDescUpdatedAt.Default.(func() time.Time)
	// dictionary.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	dictionary.UpdateDefaultUpdatedAt = dictionaryDescUpdatedAt.UpdateDefault.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[0].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[1].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = userDescPasswordHash.Validators[0].(func(string) error)
	// userDescIsAdmin is the schema descriptor for is_admin field.
	userDescIsAdmin := userFields[2].Descriptor()
	// user.DefaultIsAdmin holds the default value on creation for the is_admin field.
	user.DefaultIsAdmin = userDescIsAdmin.Default.(bool)
}
