// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"owl/backend/ent/font"
	"owl/backend/ent/user"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// User is the model entity for the User schema.
type User struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Username holds the value of the "username" field.
	Username string `json:"username,omitempty"`
	// DisplayName holds the value of the "display_name" field.
	DisplayName string `json:"display_name,omitempty"`
	// AvatarName holds the value of the "avatar_name" field.
	AvatarName string `json:"avatar_name,omitempty"`
	// AvatarPath holds the value of the "avatar_path" field.
	AvatarPath string `json:"avatar_path,omitempty"`
	// AvatarMime holds the value of the "avatar_mime" field.
	AvatarMime string `json:"avatar_mime,omitempty"`
	// PasswordHash holds the value of the "password_hash" field.
	PasswordHash string `json:"-"`
	// IsAdmin holds the value of the "is_admin" field.
	IsAdmin bool `json:"is_admin,omitempty"`
	// Language holds the value of the "language" field.
	Language string `json:"language,omitempty"`
	// Theme holds the value of the "theme" field.
	Theme string `json:"theme,omitempty"`
	// FontMode holds the value of the "font_mode" field.
	FontMode string `json:"font_mode,omitempty"`
	// McpTokenHash holds the value of the "mcp_token_hash" field.
	McpTokenHash string `json:"-"`
	// McpTokenHint holds the value of the "mcp_token_hint" field.
	McpTokenHint string `json:"mcp_token_hint,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserQuery when eager-loading is set.
	Edges              UserEdges `json:"edges"`
	user_selected_font *int
	selectValues       sql.SelectValues
}

// UserEdges holds the relations/edges for other nodes in the graph.
type UserEdges struct {
	// Dictionaries holds the value of the dictionaries edge.
	Dictionaries []*Dictionary `json:"dictionaries,omitempty"`
	// SelectedFont holds the value of the selected_font edge.
	SelectedFont *Font `json:"selected_font,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// DictionariesOrErr returns the Dictionaries value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) DictionariesOrErr() ([]*Dictionary, error) {
	if e.loadedTypes[0] {
		return e.Dictionaries, nil
	}
	return nil, &NotLoadedError{edge: "dictionaries"}
}

// SelectedFontOrErr returns the SelectedFont value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserEdges) SelectedFontOrErr() (*Font, error) {
	if e.SelectedFont != nil {
		return e.SelectedFont, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: font.Label}
	}
	return nil, &NotLoadedError{edge: "selected_font"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*User) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case user.FieldIsAdmin:
			values[i] = new(sql.NullBool)
		case user.FieldID:
			values[i] = new(sql.NullInt64)
		case user.FieldUsername, user.FieldDisplayName, user.FieldAvatarName, user.FieldAvatarPath, user.FieldAvatarMime, user.FieldPasswordHash, user.FieldLanguage, user.FieldTheme, user.FieldFontMode, user.FieldMcpTokenHash, user.FieldMcpTokenHint:
			values[i] = new(sql.NullString)
		case user.ForeignKeys[0]: // user_selected_font
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the User fields.
func (_m *User) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case user.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case user.FieldUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field username", values[i])
			} else if value.Valid {
				_m.Username = value.String
			}
		case user.FieldDisplayName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field display_name", values[i])
			} else if value.Valid {
				_m.DisplayName = value.String
			}
		case user.FieldAvatarName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field avatar_name", values[i])
			} else if value.Valid {
				_m.AvatarName = value.String
			}
		case user.FieldAvatarPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field avatar_path", values[i])
			} else if value.Valid {
				_m.AvatarPath = value.String
			}
		case user.FieldAvatarMime:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field avatar_mime", values[i])
			} else if value.Valid {
				_m.AvatarMime = value.String
			}
		case user.FieldPasswordHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field password_hash", values[i])
			} else if value.Valid {
				_m.PasswordHash = value.String
			}
		case user.FieldIsAdmin:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_admin", values[i])
			} else if value.Valid {
				_m.IsAdmin = value.Bool
			}
		case user.FieldLanguage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field language", values[i])
			} else if value.Valid {
				_m.Language = value.String
			}
		case user.FieldTheme:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field theme", values[i])
			} else if value.Valid {
				_m.Theme = value.String
			}
		case user.FieldFontMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field font_mode", values[i])
			} else if value.Valid {
				_m.FontMode = value.String
			}
		case user.FieldMcpTokenHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mcp_token_hash", values[i])
			} else if value.Valid {
				_m.McpTokenHash = value.String
			}
		case user.FieldMcpTokenHint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mcp_token_hint", values[i])
			} else if value.Valid {
				_m.McpTokenHint = value.String
			}
		case user.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_selected_font", value)
			} else if value.Valid {
				_m.user_selected_font = new(int)
				*_m.user_selected_font = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the User.
// This includes values selected through modifiers, order, etc.
func (_m *User) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryDictionaries queries the "dictionaries" edge of the User entity.
func (_m *User) QueryDictionaries() *DictionaryQuery {
	return NewUserClient(_m.config).QueryDictionaries(_m)
}

// QuerySelectedFont queries the "selected_font" edge of the User entity.
func (_m *User) QuerySelectedFont() *FontQuery {
	return NewUserClient(_m.config).QuerySelectedFont(_m)
}

// Update returns a builder for updating this User.
// Note that you need to call User.Unwrap() before calling this method if this User
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *User) Update() *UserUpdateOne {
	return NewUserClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the User entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *User) Unwrap() *User {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: User is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *User) String() string {
	var builder strings.Builder
	builder.WriteString("User(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("username=")
	builder.WriteString(_m.Username)
	builder.WriteString(", ")
	builder.WriteString("display_name=")
	builder.WriteString(_m.DisplayName)
	builder.WriteString(", ")
	builder.WriteString("avatar_name=")
	builder.WriteString(_m.AvatarName)
	builder.WriteString(", ")
	builder.WriteString("avatar_path=")
	builder.WriteString(_m.AvatarPath)
	builder.WriteString(", ")
	builder.WriteString("avatar_mime=")
	builder.WriteString(_m.AvatarMime)
	builder.WriteString(", ")
	builder.WriteString("password_hash=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("is_admin=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsAdmin))
	builder.WriteString(", ")
	builder.WriteString("language=")
	builder.WriteString(_m.Language)
	builder.WriteString(", ")
	builder.WriteString("theme=")
	builder.WriteString(_m.Theme)
	builder.WriteString(", ")
	builder.WriteString("font_mode=")
	builder.WriteString(_m.FontMode)
	builder.WriteString(", ")
	builder.WriteString("mcp_token_hash=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("mcp_token_hint=")
	builder.WriteString(_m.McpTokenHint)
	builder.WriteByte(')')
	return builder.String()
}

// Users is a parsable slice of User.
type Users []*User
