// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"owl/backend/ent/dictionary"
	"owl/backend/ent/font"
	"owl/backend/ent/user"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserCreate is the builder for creating a User entity.
type UserCreate struct {
	config
	mutation *UserMutation
	hooks    []Hook
}

// SetUsername sets the "username" field.
func (_c *UserCreate) SetUsername(v string) *UserCreate {
	_c.mutation.SetUsername(v)
	return _c
}

// SetDisplayName sets the "display_name" field.
func (_c *UserCreate) SetDisplayName(v string) *UserCreate {
	_c.mutation.SetDisplayName(v)
	return _c
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_c *UserCreate) SetNillableDisplayName(v *string) *UserCreate {
	if v != nil {
		_c.SetDisplayName(*v)
	}
	return _c
}

// SetAvatarName sets the "avatar_name" field.
func (_c *UserCreate) SetAvatarName(v string) *UserCreate {
	_c.mutation.SetAvatarName(v)
	return _c
}

// SetNillableAvatarName sets the "avatar_name" field if the given value is not nil.
func (_c *UserCreate) SetNillableAvatarName(v *string) *UserCreate {
	if v != nil {
		_c.SetAvatarName(*v)
	}
	return _c
}

// SetAvatarPath sets the "avatar_path" field.
func (_c *UserCreate) SetAvatarPath(v string) *UserCreate {
	_c.mutation.SetAvatarPath(v)
	return _c
}

// SetNillableAvatarPath sets the "avatar_path" field if the given value is not nil.
func (_c *UserCreate) SetNillableAvatarPath(v *string) *UserCreate {
	if v != nil {
		_c.SetAvatarPath(*v)
	}
	return _c
}

// SetAvatarMime sets the "avatar_mime" field.
func (_c *UserCreate) SetAvatarMime(v string) *UserCreate {
	_c.mutation.SetAvatarMime(v)
	return _c
}

// SetNillableAvatarMime sets the "avatar_mime" field if the given value is not nil.
func (_c *UserCreate) SetNillableAvatarMime(v *string) *UserCreate {
	if v != nil {
		_c.SetAvatarMime(*v)
	}
	return _c
}

// SetPasswordHash sets the "password_hash" field.
func (_c *UserCreate) SetPasswordHash(v string) *UserCreate {
	_c.mutation.SetPasswordHash(v)
	return _c
}

// SetIsAdmin sets the "is_admin" field.
func (_c *UserCreate) SetIsAdmin(v bool) *UserCreate {
	_c.mutation.SetIsAdmin(v)
	return _c
}

// SetNillableIsAdmin sets the "is_admin" field if the given value is not nil.
func (_c *UserCreate) SetNillableIsAdmin(v *bool) *UserCreate {
	if v != nil {
		_c.SetIsAdmin(*v)
	}
	return _c
}

// SetLanguage sets the "language" field.
func (_c *UserCreate) SetLanguage(v string) *UserCreate {
	_c.mutation.SetLanguage(v)
	return _c
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_c *UserCreate) SetNillableLanguage(v *string) *UserCreate {
	if v != nil {
		_c.SetLanguage(*v)
	}
	return _c
}

// SetTheme sets the "theme" field.
func (_c *UserCreate) SetTheme(v string) *UserCreate {
	_c.mutation.SetTheme(v)
	return _c
}

// SetNillableTheme sets the "theme" field if the given value is not nil.
func (_c *UserCreate) SetNillableTheme(v *string) *UserCreate {
	if v != nil {
		_c.SetTheme(*v)
	}
	return _c
}

// SetFontMode sets the "font_mode" field.
func (_c *UserCreate) SetFontMode(v string) *UserCreate {
	_c.mutation.SetFontMode(v)
	return _c
}

// SetNillableFontMode sets the "font_mode" field if the given value is not nil.
func (_c *UserCreate) SetNillableFontMode(v *string) *UserCreate {
	if v != nil {
		_c.SetFontMode(*v)
	}
	return _c
}

// SetMcpTokenHash sets the "mcp_token_hash" field.
func (_c *UserCreate) SetMcpTokenHash(v string) *UserCreate {
	_c.mutation.SetMcpTokenHash(v)
	return _c
}

// SetNillableMcpTokenHash sets the "mcp_token_hash" field if the given value is not nil.
func (_c *UserCreate) SetNillableMcpTokenHash(v *string) *UserCreate {
	if v != nil {
		_c.SetMcpTokenHash(*v)
	}
	return _c
}

// SetMcpTokenHint sets the "mcp_token_hint" field.
func (_c *UserCreate) SetMcpTokenHint(v string) *UserCreate {
	_c.mutation.SetMcpTokenHint(v)
	return _c
}

// SetNillableMcpTokenHint sets the "mcp_token_hint" field if the given value is not nil.
func (_c *UserCreate) SetNillableMcpTokenHint(v *string) *UserCreate {
	if v != nil {
		_c.SetMcpTokenHint(*v)
	}
	return _c
}

// AddDictionaryIDs adds the "dictionaries" edge to the Dictionary entity by IDs.
func (_c *UserCreate) AddDictionaryIDs(ids ...int) *UserCreate {
	_c.mutation.AddDictionaryIDs(ids...)
	return _c
}

// AddDictionaries adds the "dictionaries" edges to the Dictionary entity.
func (_c *UserCreate) AddDictionaries(v ...*Dictionary) *UserCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddDictionaryIDs(ids...)
}

// SetSelectedFontID sets the "selected_font" edge to the Font entity by ID.
func (_c *UserCreate) SetSelectedFontID(id int) *UserCreate {
	_c.mutation.SetSelectedFontID(id)
	return _c
}

// SetNillableSelectedFontID sets the "selected_font" edge to the Font entity by ID if the given value is not nil.
func (_c *UserCreate) SetNillableSelectedFontID(id *int) *UserCreate {
	if id != nil {
		_c = _c.SetSelectedFontID(*id)
	}
	return _c
}

// SetSelectedFont sets the "selected_font" edge to the Font entity.
func (_c *UserCreate) SetSelectedFont(v *Font) *UserCreate {
	return _c.SetSelectedFontID(v.ID)
}

// Mutation returns the UserMutation object of the builder.
func (_c *UserCreate) Mutation() *UserMutation {
	return _c.mutation
}

// Save creates the User in the database.
func (_c *UserCreate) Save(ctx context.Context) (*User, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserCreate) SaveX(ctx context.Context) *User {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserCreate) defaults() {
	if _, ok := _c.mutation.DisplayName(); !ok {
		v := user.DefaultDisplayName
		_c.mutation.SetDisplayName(v)
	}
	if _, ok := _c.mutation.AvatarName(); !ok {
		v := user.DefaultAvatarName
		_c.mutation.SetAvatarName(v)
	}
	if _, ok := _c.mutation.AvatarPath(); !ok {
		v := user.DefaultAvatarPath
		_c.mutation.SetAvatarPath(v)
	}
	if _, ok := _c.mutation.AvatarMime(); !ok {
		v := user.DefaultAvatarMime
		_c.mutation.SetAvatarMime(v)
	}
	if _, ok := _c.mutation.IsAdmin(); !ok {
		v := user.DefaultIsAdmin
		_c.mutation.SetIsAdmin(v)
	}
	if _, ok := _c.mutation.Language(); !ok {
		v := user.DefaultLanguage
		_c.mutation.SetLanguage(v)
	}
	if _, ok := _c.mutation.Theme(); !ok {
		v := user.DefaultTheme
		_c.mutation.SetTheme(v)
	}
	if _, ok := _c.mutation.FontMode(); !ok {
		v := user.DefaultFontMode
		_c.mutation.SetFontMode(v)
	}
	if _, ok := _c.mutation.McpTokenHash(); !ok {
		v := user.DefaultMcpTokenHash
		_c.mutation.SetMcpTokenHash(v)
	}
	if _, ok := _c.mutation.McpTokenHint(); !ok {
		v := user.DefaultMcpTokenHint
		_c.mutation.SetMcpTokenHint(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserCreate) check() error {
	if _, ok := _c.mutation.Username(); !ok {
		return &ValidationError{Name: "username", err: errors.New(`ent: missing required field "User.username"`)}
	}
	if v, ok := _c.mutation.Username(); ok {
		if err := user.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "User.username": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DisplayName(); !ok {
		return &ValidationError{Name: "display_name", err: errors.New(`ent: missing required field "User.display_name"`)}
	}
	if _, ok := _c.mutation.AvatarName(); !ok {
		return &ValidationError{Name: "avatar_name", err: errors.New(`ent: missing required field "User.avatar_name"`)}
	}
	if _, ok := _c.mutation.AvatarPath(); !ok {
		return &ValidationError{Name: "avatar_path", err: errors.New(`ent: missing required field "User.avatar_path"`)}
	}
	if _, ok := _c.mutation.AvatarMime(); !ok {
		return &ValidationError{Name: "avatar_mime", err: errors.New(`ent: missing required field "User.avatar_mime"`)}
	}
	if _, ok := _c.mutation.PasswordHash(); !ok {
		return &ValidationError{Name: "password_hash", err: errors.New(`ent: missing required field "User.password_hash"`)}
	}
	if v, ok := _c.mutation.PasswordHash(); ok {
		if err := user.PasswordHashValidator(v); err != nil {
			return &ValidationError{Name: "password_hash", err: fmt.Errorf(`ent: validator failed for field "User.password_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsAdmin(); !ok {
		return &ValidationError{Name: "is_admin", err: errors.New(`ent: missing required field "User.is_admin"`)}
	}
	if _, ok := _c.mutation.Language(); !ok {
		return &ValidationError{Name: "language", err: errors.New(`ent: missing required field "User.language"`)}
	}
	if _, ok := _c.mutation.Theme(); !ok {
		return &ValidationError{Name: "theme", err: errors.New(`ent: missing required field "User.theme"`)}
	}
	if _, ok := _c.mutation.FontMode(); !ok {
		return &ValidationError{Name: "font_mode", err: errors.New(`ent: missing required field "User.font_mode"`)}
	}
	if _, ok := _c.mutation.McpTokenHash(); !ok {
		return &ValidationError{Name: "mcp_token_hash", err: errors.New(`ent: missing required field "User.mcp_token_hash"`)}
	}
	if _, ok := _c.mutation.McpTokenHint(); !ok {
		return &ValidationError{Name: "mcp_token_hint", err: errors.New(`ent: missing required field "User.mcp_token_hint"`)}
	}
	return nil
}

func (_c *UserCreate) sqlSave(ctx context.Context) (*User, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserCreate) createSpec() (*User, *sqlgraph.CreateSpec) {
	var (
		_node = &User{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(user.Table, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Username(); ok {
		_spec.SetField(user.FieldUsername, field.TypeString, value)
		_node.Username = value
	}
	if value, ok := _c.mutation.DisplayName(); ok {
		_spec.SetField(user.FieldDisplayName, field.TypeString, value)
		_node.DisplayName = value
	}
	if value, ok := _c.mutation.AvatarName(); ok {
		_spec.SetField(user.FieldAvatarName, field.TypeString, value)
		_node.AvatarName = value
	}
	if value, ok := _c.mutation.AvatarPath(); ok {
		_spec.SetField(user.FieldAvatarPath, field.TypeString, value)
		_node.AvatarPath = value
	}
	if value, ok := _c.mutation.AvatarMime(); ok {
		_spec.SetField(user.FieldAvatarMime, field.TypeString, value)
		_node.AvatarMime = value
	}
	if value, ok := _c.mutation.PasswordHash(); ok {
		_spec.SetField(user.FieldPasswordHash, field.TypeString, value)
		_node.PasswordHash = value
	}
	if value, ok := _c.mutation.IsAdmin(); ok {
		_spec.SetField(user.FieldIsAdmin, field.TypeBool, value)
		_node.IsAdmin = value
	}
	if value, ok := _c.mutation.Language(); ok {
		_spec.SetField(user.FieldLanguage, field.TypeString, value)
		_node.Language = value
	}
	if value, ok := _c.mutation.Theme(); ok {
		_spec.SetField(user.FieldTheme, field.TypeString, value)
		_node.Theme = value
	}
	if value, ok := _c.mutation.FontMode(); ok {
		_spec.SetField(user.FieldFontMode, field.TypeString, value)
		_node.FontMode = value
	}
	if value, ok := _c.mutation.McpTokenHash(); ok {
		_spec.SetField(user.FieldMcpTokenHash, field.TypeString, value)
		_node.McpTokenHash = value
	}
	if value, ok := _c.mutation.McpTokenHint(); ok {
		_spec.SetField(user.FieldMcpTokenHint, field.TypeString, value)
		_node.McpTokenHint = value
	}
	if nodes := _c.mutation.DictionariesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.DictionariesTable,
			Columns: []string{user.DictionariesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dictionary.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SelectedFontIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   user.SelectedFontTable,
			Columns: []string{user.SelectedFontColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(font.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_selected_font = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UserCreateBulk is the builder for creating many User entities in bulk.
type UserCreateBulk struct {
	config
	err      error
	builders []*UserCreate
}

// Save creates the User entities in the database.
func (_c *UserCreateBulk) Save(ctx context.Context) ([]*User, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*User, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserCreateBulk) SaveX(ctx context.Context) []*User {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
