// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"owl/backend/ent/dictionary"
	"owl/backend/ent/predicate"
	"owl/backend/ent/user"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUsername sets the "username" field.
func (_u *UserUpdate) SetUsername(v string) *UserUpdate {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *UserUpdate) SetNillableUsername(v *string) *UserUpdate {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *UserUpdate) SetPasswordHash(v string) *UserUpdate {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *UserUpdate) SetNillablePasswordHash(v *string) *UserUpdate {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// SetIsAdmin sets the "is_admin" field.
func (_u *UserUpdate) SetIsAdmin(v bool) *UserUpdate {
	_u.mutation.SetIsAdmin(v)
	return _u
}

// SetNillableIsAdmin sets the "is_admin" field if the given value is not nil.
func (_u *UserUpdate) SetNillableIsAdmin(v *bool) *UserUpdate {
	if v != nil {
		_u.SetIsAdmin(*v)
	}
	return _u
}

// SetLanguage sets the "language" field.
func (_u *UserUpdate) SetLanguage(v string) *UserUpdate {
	_u.mutation.SetLanguage(v)
	return _u
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_u *UserUpdate) SetNillableLanguage(v *string) *UserUpdate {
	if v != nil {
		_u.SetLanguage(*v)
	}
	return _u
}

// SetTheme sets the "theme" field.
func (_u *UserUpdate) SetTheme(v string) *UserUpdate {
	_u.mutation.SetTheme(v)
	return _u
}

// SetNillableTheme sets the "theme" field if the given value is not nil.
func (_u *UserUpdate) SetNillableTheme(v *string) *UserUpdate {
	if v != nil {
		_u.SetTheme(*v)
	}
	return _u
}

// SetFontMode sets the "font_mode" field.
func (_u *UserUpdate) SetFontMode(v string) *UserUpdate {
	_u.mutation.SetFontMode(v)
	return _u
}

// SetNillableFontMode sets the "font_mode" field if the given value is not nil.
func (_u *UserUpdate) SetNillableFontMode(v *string) *UserUpdate {
	if v != nil {
		_u.SetFontMode(*v)
	}
	return _u
}

// SetCustomFontName sets the "custom_font_name" field.
func (_u *UserUpdate) SetCustomFontName(v string) *UserUpdate {
	_u.mutation.SetCustomFontName(v)
	return _u
}

// SetNillableCustomFontName sets the "custom_font_name" field if the given value is not nil.
func (_u *UserUpdate) SetNillableCustomFontName(v *string) *UserUpdate {
	if v != nil {
		_u.SetCustomFontName(*v)
	}
	return _u
}

// SetCustomFontPath sets the "custom_font_path" field.
func (_u *UserUpdate) SetCustomFontPath(v string) *UserUpdate {
	_u.mutation.SetCustomFontPath(v)
	return _u
}

// SetNillableCustomFontPath sets the "custom_font_path" field if the given value is not nil.
func (_u *UserUpdate) SetNillableCustomFontPath(v *string) *UserUpdate {
	if v != nil {
		_u.SetCustomFontPath(*v)
	}
	return _u
}

// SetCustomFontFamily sets the "custom_font_family" field.
func (_u *UserUpdate) SetCustomFontFamily(v string) *UserUpdate {
	_u.mutation.SetCustomFontFamily(v)
	return _u
}

// SetNillableCustomFontFamily sets the "custom_font_family" field if the given value is not nil.
func (_u *UserUpdate) SetNillableCustomFontFamily(v *string) *UserUpdate {
	if v != nil {
		_u.SetCustomFontFamily(*v)
	}
	return _u
}

// AddDictionaryIDs adds the "dictionaries" edge to the Dictionary entity by IDs.
func (_u *UserUpdate) AddDictionaryIDs(ids ...int) *UserUpdate {
	_u.mutation.AddDictionaryIDs(ids...)
	return _u
}

// AddDictionaries adds the "dictionaries" edges to the Dictionary entity.
func (_u *UserUpdate) AddDictionaries(v ...*Dictionary) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDictionaryIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdate) Mutation() *UserMutation {
	return _u.mutation
}

// ClearDictionaries clears all "dictionaries" edges to the Dictionary entity.
func (_u *UserUpdate) ClearDictionaries() *UserUpdate {
	_u.mutation.ClearDictionaries()
	return _u
}

// RemoveDictionaryIDs removes the "dictionaries" edge to Dictionary entities by IDs.
func (_u *UserUpdate) RemoveDictionaryIDs(ids ...int) *UserUpdate {
	_u.mutation.RemoveDictionaryIDs(ids...)
	return _u
}

// RemoveDictionaries removes "dictionaries" edges to Dictionary entities.
func (_u *UserUpdate) RemoveDictionaries(v ...*Dictionary) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDictionaryIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdate) check() error {
	if v, ok := _u.mutation.Username(); ok {
		if err := user.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "User.username": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PasswordHash(); ok {
		if err := user.PasswordHashValidator(v); err != nil {
			return &ValidationError{Name: "password_hash", err: fmt.Errorf(`ent: validator failed for field "User.password_hash": %w`, err)}
		}
	}
	return nil
}

func (_u *UserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(user.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(user.FieldPasswordHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsAdmin(); ok {
		_spec.SetField(user.FieldIsAdmin, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Language(); ok {
		_spec.SetField(user.FieldLanguage, field.TypeString, value)
	}
	if value, ok := _u.mutation.Theme(); ok {
		_spec.SetField(user.FieldTheme, field.TypeString, value)
	}
	if value, ok := _u.mutation.FontMode(); ok {
		_spec.SetField(user.FieldFontMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.CustomFontName(); ok {
		_spec.SetField(user.FieldCustomFontName, field.TypeString, value)
	}
	if value, ok := _u.mutation.CustomFontPath(); ok {
		_spec.SetField(user.FieldCustomFontPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.CustomFontFamily(); ok {
		_spec.SetField(user.FieldCustomFontFamily, field.TypeString, value)
	}
	if _u.mutation.DictionariesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.DictionariesTable,
			Columns: []string{user.DictionariesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dictionary.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDictionariesIDs(); len(nodes) > 0 && !_u.mutation.DictionariesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.DictionariesTable,
			Columns: []string{user.DictionariesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dictionary.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DictionariesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.DictionariesTable,
			Columns: []string{user.DictionariesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dictionary.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserMutation
}

// SetUsername sets the "username" field.
func (_u *UserUpdateOne) SetUsername(v string) *UserUpdateOne {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableUsername(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *UserUpdateOne) SetPasswordHash(v string) *UserUpdateOne {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillablePasswordHash(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// SetIsAdmin sets the "is_admin" field.
func (_u *UserUpdateOne) SetIsAdmin(v bool) *UserUpdateOne {
	_u.mutation.SetIsAdmin(v)
	return _u
}

// SetNillableIsAdmin sets the "is_admin" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableIsAdmin(v *bool) *UserUpdateOne {
	if v != nil {
		_u.SetIsAdmin(*v)
	}
	return _u
}

// SetLanguage sets the "language" field.
func (_u *UserUpdateOne) SetLanguage(v string) *UserUpdateOne {
	_u.mutation.SetLanguage(v)
	return _u
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableLanguage(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetLanguage(*v)
	}
	return _u
}

// SetTheme sets the "theme" field.
func (_u *UserUpdateOne) SetTheme(v string) *UserUpdateOne {
	_u.mutation.SetTheme(v)
	return _u
}

// SetNillableTheme sets the "theme" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableTheme(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetTheme(*v)
	}
	return _u
}

// SetFontMode sets the "font_mode" field.
func (_u *UserUpdateOne) SetFontMode(v string) *UserUpdateOne {
	_u.mutation.SetFontMode(v)
	return _u
}

// SetNillableFontMode sets the "font_mode" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableFontMode(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetFontMode(*v)
	}
	return _u
}

// SetCustomFontName sets the "custom_font_name" field.
func (_u *UserUpdateOne) SetCustomFontName(v string) *UserUpdateOne {
	_u.mutation.SetCustomFontName(v)
	return _u
}

// SetNillableCustomFontName sets the "custom_font_name" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableCustomFontName(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetCustomFontName(*v)
	}
	return _u
}

// SetCustomFontPath sets the "custom_font_path" field.
func (_u *UserUpdateOne) SetCustomFontPath(v string) *UserUpdateOne {
	_u.mutation.SetCustomFontPath(v)
	return _u
}

// SetNillableCustomFontPath sets the "custom_font_path" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableCustomFontPath(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetCustomFontPath(*v)
	}
	return _u
}

// SetCustomFontFamily sets the "custom_font_family" field.
func (_u *UserUpdateOne) SetCustomFontFamily(v string) *UserUpdateOne {
	_u.mutation.SetCustomFontFamily(v)
	return _u
}

// SetNillableCustomFontFamily sets the "custom_font_family" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableCustomFontFamily(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetCustomFontFamily(*v)
	}
	return _u
}

// AddDictionaryIDs adds the "dictionaries" edge to the Dictionary entity by IDs.
func (_u *UserUpdateOne) AddDictionaryIDs(ids ...int) *UserUpdateOne {
	_u.mutation.AddDictionaryIDs(ids...)
	return _u
}

// AddDictionaries adds the "dictionaries" edges to the Dictionary entity.
func (_u *UserUpdateOne) AddDictionaries(v ...*Dictionary) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDictionaryIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdateOne) Mutation() *UserMutation {
	return _u.mutation
}

// ClearDictionaries clears all "dictionaries" edges to the Dictionary entity.
func (_u *UserUpdateOne) ClearDictionaries() *UserUpdateOne {
	_u.mutation.ClearDictionaries()
	return _u
}

// RemoveDictionaryIDs removes the "dictionaries" edge to Dictionary entities by IDs.
func (_u *UserUpdateOne) RemoveDictionaryIDs(ids ...int) *UserUpdateOne {
	_u.mutation.RemoveDictionaryIDs(ids...)
	return _u
}

// RemoveDictionaries removes "dictionaries" edges to Dictionary entities.
func (_u *UserUpdateOne) RemoveDictionaries(v ...*Dictionary) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDictionaryIDs(ids...)
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdateOne) Where(ps ...predicate.User) *UserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated User entity.
func (_u *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdateOne) check() error {
	if v, ok := _u.mutation.Username(); ok {
		if err := user.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "User.username": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PasswordHash(); ok {
		if err := user.PasswordHashValidator(v); err != nil {
			return &ValidationError{Name: "password_hash", err: fmt.Errorf(`ent: validator failed for field "User.password_hash": %w`, err)}
		}
	}
	return nil
}

func (_u *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for _, f := range fields {
			if !user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(user.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(user.FieldPasswordHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsAdmin(); ok {
		_spec.SetField(user.FieldIsAdmin, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Language(); ok {
		_spec.SetField(user.FieldLanguage, field.TypeString, value)
	}
	if value, ok := _u.mutation.Theme(); ok {
		_spec.SetField(user.FieldTheme, field.TypeString, value)
	}
	if value, ok := _u.mutation.FontMode(); ok {
		_spec.SetField(user.FieldFontMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.CustomFontName(); ok {
		_spec.SetField(user.FieldCustomFontName, field.TypeString, value)
	}
	if value, ok := _u.mutation.CustomFontPath(); ok {
		_spec.SetField(user.FieldCustomFontPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.CustomFontFamily(); ok {
		_spec.SetField(user.FieldCustomFontFamily, field.TypeString, value)
	}
	if _u.mutation.DictionariesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.DictionariesTable,
			Columns: []string{user.DictionariesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dictionary.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDictionariesIDs(); len(nodes) > 0 && !_u.mutation.DictionariesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.DictionariesTable,
			Columns: []string{user.DictionariesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dictionary.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DictionariesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.DictionariesTable,
			Columns: []string{user.DictionariesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dictionary.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &User{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
