// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// DictionariesColumns holds the columns for the "dictionaries" table.
	DictionariesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "title", Type: field.TypeString, Default: ""},
		{Name: "description", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "slug", Type: field.TypeString},
		{Name: "mdx_path", Type: field.TypeString, Size: 2147483647},
		{Name: "mdd_paths_json", Type: field.TypeString, Size: 2147483647, Default: "[]"},
		{Name: "entry_count", Type: field.TypeInt, Default: 0},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "public", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_dictionaries", Type: field.TypeInt},
	}
	// DictionariesTable holds the schema information for the "dictionaries" table.
	DictionariesTable = &schema.Table{
		Name:       "dictionaries",
		Columns:    DictionariesColumns,
		PrimaryKey: []*schema.Column{DictionariesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "dictionaries_users_dictionaries",
				Columns:    []*schema.Column{DictionariesColumns[12]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "dictionary_enabled_public_title",
				Unique:  false,
				Columns: []*schema.Column{DictionariesColumns[8], DictionariesColumns[9], DictionariesColumns[2]},
			},
			{
				Name:    "dictionary_enabled_title",
				Unique:  false,
				Columns: []*schema.Column{DictionariesColumns[8], DictionariesColumns[2]},
			},
			{
				Name:    "dictionary_created_at",
				Unique:  false,
				Columns: []*schema.Column{DictionariesColumns[10]},
			},
			{
				Name:    "dictionary_slug",
				Unique:  false,
				Columns: []*schema.Column{DictionariesColumns[4]},
			},
			{
				Name:    "dictionary_user_dictionaries",
				Unique:  false,
				Columns: []*schema.Column{DictionariesColumns[12]},
			},
		},
	}
	// DictionaryIndexEntriesColumns holds the columns for the "dictionary_index_entries" table.
	DictionaryIndexEntriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "dictionary_name", Type: field.TypeString},
		{Name: "keyword", Type: field.TypeString},
		{Name: "normalized_keyword", Type: field.TypeString, Default: ""},
		{Name: "lookup_key", Type: field.TypeString},
		{Name: "lookup_key_lower", Type: field.TypeString},
		{Name: "record_start_offset", Type: field.TypeInt64},
		{Name: "record_end_offset", Type: field.TypeInt64},
		{Name: "key_block_idx", Type: field.TypeInt64},
		{Name: "is_resource", Type: field.TypeBool, Default: false},
		{Name: "payload", Type: field.TypeString, Size: 2147483647},
	}
	// DictionaryIndexEntriesTable holds the schema information for the "dictionary_index_entries" table.
	DictionaryIndexEntriesTable = &schema.Table{
		Name:       "dictionary_index_entries",
		Columns:    DictionaryIndexEntriesColumns,
		PrimaryKey: []*schema.Column{DictionaryIndexEntriesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "dictionaryindexentry_dictionary_name",
				Unique:  false,
				Columns: []*schema.Column{DictionaryIndexEntriesColumns[1]},
			},
			{
				Name:    "dictionaryindexentry_dictionary_name_lookup_key",
				Unique:  false,
				Columns: []*schema.Column{DictionaryIndexEntriesColumns[1], DictionaryIndexEntriesColumns[4]},
			},
			{
				Name:    "dictionaryindexentry_dictionary_name_lookup_key_lower",
				Unique:  false,
				Columns: []*schema.Column{DictionaryIndexEntriesColumns[1], DictionaryIndexEntriesColumns[5]},
			},
		},
	}
	// DictionaryIndexManifestsColumns holds the columns for the "dictionary_index_manifests" table.
	DictionaryIndexManifestsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "dictionary_name", Type: field.TypeString, Unique: true},
		{Name: "source_path", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "fingerprint", Type: field.TypeString, Default: ""},
		{Name: "schema_version", Type: field.TypeString, Default: ""},
		{Name: "built_at", Type: field.TypeTime},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true},
	}
	// DictionaryIndexManifestsTable holds the schema information for the "dictionary_index_manifests" table.
	DictionaryIndexManifestsTable = &schema.Table{
		Name:       "dictionary_index_manifests",
		Columns:    DictionaryIndexManifestsColumns,
		PrimaryKey: []*schema.Column{DictionaryIndexManifestsColumns[0]},
	}
	// FontsColumns holds the columns for the "fonts" table.
	FontsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "family", Type: field.TypeString},
		{Name: "path", Type: field.TypeString, Size: 2147483647},
		{Name: "mime", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// FontsTable holds the schema information for the "fonts" table.
	FontsTable = &schema.Table{
		Name:       "fonts",
		Columns:    FontsColumns,
		PrimaryKey: []*schema.Column{FontsColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "display_name", Type: field.TypeString, Default: ""},
		{Name: "avatar_name", Type: field.TypeString, Default: ""},
		{Name: "avatar_path", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "avatar_mime", Type: field.TypeString, Default: ""},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "is_admin", Type: field.TypeBool, Default: false},
		{Name: "language", Type: field.TypeString, Default: "zh-CN"},
		{Name: "theme", Type: field.TypeString, Default: "system"},
		{Name: "font_mode", Type: field.TypeString, Default: "sans"},
		{Name: "recent_search_limit", Type: field.TypeInt, Default: 8},
		{Name: "mcp_token_hash", Type: field.TypeString, Default: ""},
		{Name: "mcp_token_hint", Type: field.TypeString, Default: ""},
		{Name: "user_selected_font", Type: field.TypeInt, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "users_fonts_selected_font",
				Columns:    []*schema.Column{UsersColumns[14]},
				RefColumns: []*schema.Column{FontsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "user_mcp_token_hash",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[12]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DictionariesTable,
		DictionaryIndexEntriesTable,
		DictionaryIndexManifestsTable,
		FontsTable,
		UsersTable,
	}
)

func init() {
	DictionariesTable.ForeignKeys[0].RefTable = UsersTable
	UsersTable.ForeignKeys[0].RefTable = FontsTable
}
