// Code generated by ent, DO NOT EDIT.

package dictionaryindexentry

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the dictionaryindexentry type in the database.
	Label = "dictionary_index_entry"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDictionaryName holds the string denoting the dictionary_name field in the database.
	FieldDictionaryName = "dictionary_name"
	// FieldKeyword holds the string denoting the keyword field in the database.
	FieldKeyword = "keyword"
	// FieldNormalizedKeyword holds the string denoting the normalized_keyword field in the database.
	FieldNormalizedKeyword = "normalized_keyword"
	// FieldLookupKey holds the string denoting the lookup_key field in the database.
	FieldLookupKey = "lookup_key"
	// FieldLookupKeyLower holds the string denoting the lookup_key_lower field in the database.
	FieldLookupKeyLower = "lookup_key_lower"
	// FieldRecordStartOffset holds the string denoting the record_start_offset field in the database.
	FieldRecordStartOffset = "record_start_offset"
	// FieldRecordEndOffset holds the string denoting the record_end_offset field in the database.
	FieldRecordEndOffset = "record_end_offset"
	// FieldKeyBlockIdx holds the string denoting the key_block_idx field in the database.
	FieldKeyBlockIdx = "key_block_idx"
	// FieldIsResource holds the string denoting the is_resource field in the database.
	FieldIsResource = "is_resource"
	// FieldPayload holds the string denoting the payload field in the database.
	FieldPayload = "payload"
	// Table holds the table name of the dictionaryindexentry in the database.
	Table = "dictionary_index_entries"
)

// Columns holds all SQL columns for dictionaryindexentry fields.
var Columns = []string{
	FieldID,
	FieldDictionaryName,
	FieldKeyword,
	FieldNormalizedKeyword,
	FieldLookupKey,
	FieldLookupKeyLower,
	FieldRecordStartOffset,
	FieldRecordEndOffset,
	FieldKeyBlockIdx,
	FieldIsResource,
	FieldPayload,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DictionaryNameValidator is a validator for the "dictionary_name" field. It is called by the builders before save.
	DictionaryNameValidator func(string) error
	// KeywordValidator is a validator for the "keyword" field. It is called by the builders before save.
	KeywordValidator func(string) error
	// DefaultNormalizedKeyword holds the default value on creation for the "normalized_keyword" field.
	DefaultNormalizedKeyword string
	// LookupKeyValidator is a validator for the "lookup_key" field. It is called by the builders before save.
	LookupKeyValidator func(string) error
	// LookupKeyLowerValidator is a validator for the "lookup_key_lower" field. It is called by the builders before save.
	LookupKeyLowerValidator func(string) error
	// DefaultIsResource holds the default value on creation for the "is_resource" field.
	DefaultIsResource bool
	// PayloadValidator is a validator for the "payload" field. It is called by the builders before save.
	PayloadValidator func(string) error
)

// OrderOption defines the ordering options for the DictionaryIndexEntry queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDictionaryName orders the results by the dictionary_name field.
func ByDictionaryName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDictionaryName, opts...).ToFunc()
}

// ByKeyword orders the results by the keyword field.
func ByKeyword(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKeyword, opts...).ToFunc()
}

// ByNormalizedKeyword orders the results by the normalized_keyword field.
func ByNormalizedKeyword(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNormalizedKeyword, opts...).ToFunc()
}

// ByLookupKey orders the results by the lookup_key field.
func ByLookupKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLookupKey, opts...).ToFunc()
}

// ByLookupKeyLower orders the results by the lookup_key_lower field.
func ByLookupKeyLower(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLookupKeyLower, opts...).ToFunc()
}

// ByRecordStartOffset orders the results by the record_start_offset field.
func ByRecordStartOffset(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRecordStartOffset, opts...).ToFunc()
}

// ByRecordEndOffset orders the results by the record_end_offset field.
func ByRecordEndOffset(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRecordEndOffset, opts...).ToFunc()
}

// ByKeyBlockIdx orders the results by the key_block_idx field.
func ByKeyBlockIdx(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKeyBlockIdx, opts...).ToFunc()
}

// ByIsResource orders the results by the is_resource field.
func ByIsResource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsResource, opts...).ToFunc()
}

// ByPayload orders the results by the payload field.
func ByPayload(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPayload, opts...).ToFunc()
}
