// Code generated by ent, DO NOT EDIT.

package dictionaryindexentry

import (
	"owl/backend/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldLTE(FieldID, id))
}

// DictionaryName applies equality check predicate on the "dictionary_name" field. It's identical to DictionaryNameEQ.
func DictionaryName(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldEQ(FieldDictionaryName, v))
}

// Keyword applies equality check predicate on the "keyword" field. It's identical to KeywordEQ.
func Keyword(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldEQ(FieldKeyword, v))
}

// NormalizedKeyword applies equality check predicate on the "normalized_keyword" field. It's identical to NormalizedKeywordEQ.
func NormalizedKeyword(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldEQ(FieldNormalizedKeyword, v))
}

// LookupKey applies equality check predicate on the "lookup_key" field. It's identical to LookupKeyEQ.
func LookupKey(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldEQ(FieldLookupKey, v))
}

// LookupKeyLower applies equality check predicate on the "lookup_key_lower" field. It's identical to LookupKeyLowerEQ.
func LookupKeyLower(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldEQ(FieldLookupKeyLower, v))
}

// RecordStartOffset applies equality check predicate on the "record_start_offset" field. It's identical to RecordStartOffsetEQ.
func RecordStartOffset(v int64) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldEQ(FieldRecordStartOffset, v))
}

// RecordEndOffset applies equality check predicate on the "record_end_offset" field. It's identical to RecordEndOffsetEQ.
func RecordEndOffset(v int64) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldEQ(FieldRecordEndOffset, v))
}

// KeyBlockIdx applies equality check predicate on the "key_block_idx" field. It's identical to KeyBlockIdxEQ.
func KeyBlockIdx(v int64) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldEQ(FieldKeyBlockIdx, v))
}

// IsResource applies equality check predicate on the "is_resource" field. It's identical to IsResourceEQ.
func IsResource(v bool) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldEQ(FieldIsResource, v))
}

// Payload applies equality check predicate on the "payload" field. It's identical to PayloadEQ.
func Payload(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldEQ(FieldPayload, v))
}

// DictionaryNameEQ applies the EQ predicate on the "dictionary_name" field.
func DictionaryNameEQ(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldEQ(FieldDictionaryName, v))
}

// DictionaryNameNEQ applies the NEQ predicate on the "dictionary_name" field.
func DictionaryNameNEQ(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldNEQ(FieldDictionaryName, v))
}

// DictionaryNameIn applies the In predicate on the "dictionary_name" field.
func DictionaryNameIn(vs ...string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldIn(FieldDictionaryName, vs...))
}

// DictionaryNameNotIn applies the NotIn predicate on the "dictionary_name" field.
func DictionaryNameNotIn(vs ...string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldNotIn(FieldDictionaryName, vs...))
}

// DictionaryNameGT applies the GT predicate on the "dictionary_name" field.
func DictionaryNameGT(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldGT(FieldDictionaryName, v))
}

// DictionaryNameGTE applies the GTE predicate on the "dictionary_name" field.
func DictionaryNameGTE(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldGTE(FieldDictionaryName, v))
}

// DictionaryNameLT applies the LT predicate on the "dictionary_name" field.
func DictionaryNameLT(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldLT(FieldDictionaryName, v))
}

// DictionaryNameLTE applies the LTE predicate on the "dictionary_name" field.
func DictionaryNameLTE(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldLTE(FieldDictionaryName, v))
}

// DictionaryNameContains applies the Contains predicate on the "dictionary_name" field.
func DictionaryNameContains(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldContains(FieldDictionaryName, v))
}

// DictionaryNameHasPrefix applies the HasPrefix predicate on the "dictionary_name" field.
func DictionaryNameHasPrefix(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldHasPrefix(FieldDictionaryName, v))
}

// DictionaryNameHasSuffix applies the HasSuffix predicate on the "dictionary_name" field.
func DictionaryNameHasSuffix(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldHasSuffix(FieldDictionaryName, v))
}

// DictionaryNameEqualFold applies the EqualFold predicate on the "dictionary_name" field.
func DictionaryNameEqualFold(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldEqualFold(FieldDictionaryName, v))
}

// DictionaryNameContainsFold applies the ContainsFold predicate on the "dictionary_name" field.
func DictionaryNameContainsFold(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldContainsFold(FieldDictionaryName, v))
}

// KeywordEQ applies the EQ predicate on the "keyword" field.
func KeywordEQ(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldEQ(FieldKeyword, v))
}

// KeywordNEQ applies the NEQ predicate on the "keyword" field.
func KeywordNEQ(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldNEQ(FieldKeyword, v))
}

// KeywordIn applies the In predicate on the "keyword" field.
func KeywordIn(vs ...string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldIn(FieldKeyword, vs...))
}

// KeywordNotIn applies the NotIn predicate on the "keyword" field.
func KeywordNotIn(vs ...string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldNotIn(FieldKeyword, vs...))
}

// KeywordGT applies the GT predicate on the "keyword" field.
func KeywordGT(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldGT(FieldKeyword, v))
}

// KeywordGTE applies the GTE predicate on the "keyword" field.
func KeywordGTE(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldGTE(FieldKeyword, v))
}

// KeywordLT applies the LT predicate on the "keyword" field.
func KeywordLT(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldLT(FieldKeyword, v))
}

// KeywordLTE applies the LTE predicate on the "keyword" field.
func KeywordLTE(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldLTE(FieldKeyword, v))
}

// KeywordContains applies the Contains predicate on the "keyword" field.
func KeywordContains(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldContains(FieldKeyword, v))
}

// KeywordHasPrefix applies the HasPrefix predicate on the "keyword" field.
func KeywordHasPrefix(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldHasPrefix(FieldKeyword, v))
}

// KeywordHasSuffix applies the HasSuffix predicate on the "keyword" field.
func KeywordHasSuffix(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldHasSuffix(FieldKeyword, v))
}

// KeywordEqualFold applies the EqualFold predicate on the "keyword" field.
func KeywordEqualFold(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldEqualFold(FieldKeyword, v))
}

// KeywordContainsFold applies the ContainsFold predicate on the "keyword" field.
func KeywordContainsFold(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldContainsFold(FieldKeyword, v))
}

// NormalizedKeywordEQ applies the EQ predicate on the "normalized_keyword" field.
func NormalizedKeywordEQ(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldEQ(FieldNormalizedKeyword, v))
}

// NormalizedKeywordNEQ applies the NEQ predicate on the "normalized_keyword" field.
func NormalizedKeywordNEQ(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldNEQ(FieldNormalizedKeyword, v))
}

// NormalizedKeywordIn applies the In predicate on the "normalized_keyword" field.
func NormalizedKeywordIn(vs ...string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldIn(FieldNormalizedKeyword, vs...))
}

// NormalizedKeywordNotIn applies the NotIn predicate on the "normalized_keyword" field.
func NormalizedKeywordNotIn(vs ...string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldNotIn(FieldNormalizedKeyword, vs...))
}

// NormalizedKeywordGT applies the GT predicate on the "normalized_keyword" field.
func NormalizedKeywordGT(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldGT(FieldNormalizedKeyword, v))
}

// NormalizedKeywordGTE applies the GTE predicate on the "normalized_keyword" field.
func NormalizedKeywordGTE(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldGTE(FieldNormalizedKeyword, v))
}

// NormalizedKeywordLT applies the LT predicate on the "normalized_keyword" field.
func NormalizedKeywordLT(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldLT(FieldNormalizedKeyword, v))
}

// NormalizedKeywordLTE applies the LTE predicate on the "normalized_keyword" field.
func NormalizedKeywordLTE(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldLTE(FieldNormalizedKeyword, v))
}

// NormalizedKeywordContains applies the Contains predicate on the "normalized_keyword" field.
func NormalizedKeywordContains(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldContains(FieldNormalizedKeyword, v))
}

// NormalizedKeywordHasPrefix applies the HasPrefix predicate on the "normalized_keyword" field.
func NormalizedKeywordHasPrefix(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldHasPrefix(FieldNormalizedKeyword, v))
}

// NormalizedKeywordHasSuffix applies the HasSuffix predicate on the "normalized_keyword" field.
func NormalizedKeywordHasSuffix(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldHasSuffix(FieldNormalizedKeyword, v))
}

// NormalizedKeywordEqualFold applies the EqualFold predicate on the "normalized_keyword" field.
func NormalizedKeywordEqualFold(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldEqualFold(FieldNormalizedKeyword, v))
}

// NormalizedKeywordContainsFold applies the ContainsFold predicate on the "normalized_keyword" field.
func NormalizedKeywordContainsFold(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldContainsFold(FieldNormalizedKeyword, v))
}

// LookupKeyEQ applies the EQ predicate on the "lookup_key" field.
func LookupKeyEQ(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldEQ(FieldLookupKey, v))
}

// LookupKeyNEQ applies the NEQ predicate on the "lookup_key" field.
func LookupKeyNEQ(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldNEQ(FieldLookupKey, v))
}

// LookupKeyIn applies the In predicate on the "lookup_key" field.
func LookupKeyIn(vs ...string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldIn(FieldLookupKey, vs...))
}

// LookupKeyNotIn applies the NotIn predicate on the "lookup_key" field.
func LookupKeyNotIn(vs ...string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldNotIn(FieldLookupKey, vs...))
}

// LookupKeyGT applies the GT predicate on the "lookup_key" field.
func LookupKeyGT(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldGT(FieldLookupKey, v))
}

// LookupKeyGTE applies the GTE predicate on the "lookup_key" field.
func LookupKeyGTE(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldGTE(FieldLookupKey, v))
}

// LookupKeyLT applies the LT predicate on the "lookup_key" field.
func LookupKeyLT(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldLT(FieldLookupKey, v))
}

// LookupKeyLTE applies the LTE predicate on the "lookup_key" field.
func LookupKeyLTE(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldLTE(FieldLookupKey, v))
}

// LookupKeyContains applies the Contains predicate on the "lookup_key" field.
func LookupKeyContains(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldContains(FieldLookupKey, v))
}

// LookupKeyHasPrefix applies the HasPrefix predicate on the "lookup_key" field.
func LookupKeyHasPrefix(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldHasPrefix(FieldLookupKey, v))
}

// LookupKeyHasSuffix applies the HasSuffix predicate on the "lookup_key" field.
func LookupKeyHasSuffix(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldHasSuffix(FieldLookupKey, v))
}

// LookupKeyEqualFold applies the EqualFold predicate on the "lookup_key" field.
func LookupKeyEqualFold(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldEqualFold(FieldLookupKey, v))
}

// LookupKeyContainsFold applies the ContainsFold predicate on the "lookup_key" field.
func LookupKeyContainsFold(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldContainsFold(FieldLookupKey, v))
}

// LookupKeyLowerEQ applies the EQ predicate on the "lookup_key_lower" field.
func LookupKeyLowerEQ(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldEQ(FieldLookupKeyLower, v))
}

// LookupKeyLowerNEQ applies the NEQ predicate on the "lookup_key_lower" field.
func LookupKeyLowerNEQ(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldNEQ(FieldLookupKeyLower, v))
}

// LookupKeyLowerIn applies the In predicate on the "lookup_key_lower" field.
func LookupKeyLowerIn(vs ...string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldIn(FieldLookupKeyLower, vs...))
}

// LookupKeyLowerNotIn applies the NotIn predicate on the "lookup_key_lower" field.
func LookupKeyLowerNotIn(vs ...string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldNotIn(FieldLookupKeyLower, vs...))
}

// LookupKeyLowerGT applies the GT predicate on the "lookup_key_lower" field.
func LookupKeyLowerGT(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldGT(FieldLookupKeyLower, v))
}

// LookupKeyLowerGTE applies the GTE predicate on the "lookup_key_lower" field.
func LookupKeyLowerGTE(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldGTE(FieldLookupKeyLower, v))
}

// LookupKeyLowerLT applies the LT predicate on the "lookup_key_lower" field.
func LookupKeyLowerLT(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldLT(FieldLookupKeyLower, v))
}

// LookupKeyLowerLTE applies the LTE predicate on the "lookup_key_lower" field.
func LookupKeyLowerLTE(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldLTE(FieldLookupKeyLower, v))
}

// LookupKeyLowerContains applies the Contains predicate on the "lookup_key_lower" field.
func LookupKeyLowerContains(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldContains(FieldLookupKeyLower, v))
}

// LookupKeyLowerHasPrefix applies the HasPrefix predicate on the "lookup_key_lower" field.
func LookupKeyLowerHasPrefix(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldHasPrefix(FieldLookupKeyLower, v))
}

// LookupKeyLowerHasSuffix applies the HasSuffix predicate on the "lookup_key_lower" field.
func LookupKeyLowerHasSuffix(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldHasSuffix(FieldLookupKeyLower, v))
}

// LookupKeyLowerEqualFold applies the EqualFold predicate on the "lookup_key_lower" field.
func LookupKeyLowerEqualFold(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldEqualFold(FieldLookupKeyLower, v))
}

// LookupKeyLowerContainsFold applies the ContainsFold predicate on the "lookup_key_lower" field.
func LookupKeyLowerContainsFold(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldContainsFold(FieldLookupKeyLower, v))
}

// RecordStartOffsetEQ applies the EQ predicate on the "record_start_offset" field.
func RecordStartOffsetEQ(v int64) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldEQ(FieldRecordStartOffset, v))
}

// RecordStartOffsetNEQ applies the NEQ predicate on the "record_start_offset" field.
func RecordStartOffsetNEQ(v int64) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldNEQ(FieldRecordStartOffset, v))
}

// RecordStartOffsetIn applies the In predicate on the "record_start_offset" field.
func RecordStartOffsetIn(vs ...int64) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldIn(FieldRecordStartOffset, vs...))
}

// RecordStartOffsetNotIn applies the NotIn predicate on the "record_start_offset" field.
func RecordStartOffsetNotIn(vs ...int64) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldNotIn(FieldRecordStartOffset, vs...))
}

// RecordStartOffsetGT applies the GT predicate on the "record_start_offset" field.
func RecordStartOffsetGT(v int64) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldGT(FieldRecordStartOffset, v))
}

// RecordStartOffsetGTE applies the GTE predicate on the "record_start_offset" field.
func RecordStartOffsetGTE(v int64) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldGTE(FieldRecordStartOffset, v))
}

// RecordStartOffsetLT applies the LT predicate on the "record_start_offset" field.
func RecordStartOffsetLT(v int64) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldLT(FieldRecordStartOffset, v))
}

// RecordStartOffsetLTE applies the LTE predicate on the "record_start_offset" field.
func RecordStartOffsetLTE(v int64) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldLTE(FieldRecordStartOffset, v))
}

// RecordEndOffsetEQ applies the EQ predicate on the "record_end_offset" field.
func RecordEndOffsetEQ(v int64) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldEQ(FieldRecordEndOffset, v))
}

// RecordEndOffsetNEQ applies the NEQ predicate on the "record_end_offset" field.
func RecordEndOffsetNEQ(v int64) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldNEQ(FieldRecordEndOffset, v))
}

// RecordEndOffsetIn applies the In predicate on the "record_end_offset" field.
func RecordEndOffsetIn(vs ...int64) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldIn(FieldRecordEndOffset, vs...))
}

// RecordEndOffsetNotIn applies the NotIn predicate on the "record_end_offset" field.
func RecordEndOffsetNotIn(vs ...int64) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldNotIn(FieldRecordEndOffset, vs...))
}

// RecordEndOffsetGT applies the GT predicate on the "record_end_offset" field.
func RecordEndOffsetGT(v int64) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldGT(FieldRecordEndOffset, v))
}

// RecordEndOffsetGTE applies the GTE predicate on the "record_end_offset" field.
func RecordEndOffsetGTE(v int64) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldGTE(FieldRecordEndOffset, v))
}

// RecordEndOffsetLT applies the LT predicate on the "record_end_offset" field.
func RecordEndOffsetLT(v int64) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldLT(FieldRecordEndOffset, v))
}

// RecordEndOffsetLTE applies the LTE predicate on the "record_end_offset" field.
func RecordEndOffsetLTE(v int64) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldLTE(FieldRecordEndOffset, v))
}

// KeyBlockIdxEQ applies the EQ predicate on the "key_block_idx" field.
func KeyBlockIdxEQ(v int64) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldEQ(FieldKeyBlockIdx, v))
}

// KeyBlockIdxNEQ applies the NEQ predicate on the "key_block_idx" field.
func KeyBlockIdxNEQ(v int64) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldNEQ(FieldKeyBlockIdx, v))
}

// KeyBlockIdxIn applies the In predicate on the "key_block_idx" field.
func KeyBlockIdxIn(vs ...int64) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldIn(FieldKeyBlockIdx, vs...))
}

// KeyBlockIdxNotIn applies the NotIn predicate on the "key_block_idx" field.
func KeyBlockIdxNotIn(vs ...int64) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldNotIn(FieldKeyBlockIdx, vs...))
}

// KeyBlockIdxGT applies the GT predicate on the "key_block_idx" field.
func KeyBlockIdxGT(v int64) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldGT(FieldKeyBlockIdx, v))
}

// KeyBlockIdxGTE applies the GTE predicate on the "key_block_idx" field.
func KeyBlockIdxGTE(v int64) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldGTE(FieldKeyBlockIdx, v))
}

// KeyBlockIdxLT applies the LT predicate on the "key_block_idx" field.
func KeyBlockIdxLT(v int64) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldLT(FieldKeyBlockIdx, v))
}

// KeyBlockIdxLTE applies the LTE predicate on the "key_block_idx" field.
func KeyBlockIdxLTE(v int64) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldLTE(FieldKeyBlockIdx, v))
}

// IsResourceEQ applies the EQ predicate on the "is_resource" field.
func IsResourceEQ(v bool) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldEQ(FieldIsResource, v))
}

// IsResourceNEQ applies the NEQ predicate on the "is_resource" field.
func IsResourceNEQ(v bool) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldNEQ(FieldIsResource, v))
}

// PayloadEQ applies the EQ predicate on the "payload" field.
func PayloadEQ(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldEQ(FieldPayload, v))
}

// PayloadNEQ applies the NEQ predicate on the "payload" field.
func PayloadNEQ(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldNEQ(FieldPayload, v))
}

// PayloadIn applies the In predicate on the "payload" field.
func PayloadIn(vs ...string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldIn(FieldPayload, vs...))
}

// PayloadNotIn applies the NotIn predicate on the "payload" field.
func PayloadNotIn(vs ...string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldNotIn(FieldPayload, vs...))
}

// PayloadGT applies the GT predicate on the "payload" field.
func PayloadGT(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldGT(FieldPayload, v))
}

// PayloadGTE applies the GTE predicate on the "payload" field.
func PayloadGTE(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldGTE(FieldPayload, v))
}

// PayloadLT applies the LT predicate on the "payload" field.
func PayloadLT(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldLT(FieldPayload, v))
}

// PayloadLTE applies the LTE predicate on the "payload" field.
func PayloadLTE(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldLTE(FieldPayload, v))
}

// PayloadContains applies the Contains predicate on the "payload" field.
func PayloadContains(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldContains(FieldPayload, v))
}

// PayloadHasPrefix applies the HasPrefix predicate on the "payload" field.
func PayloadHasPrefix(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldHasPrefix(FieldPayload, v))
}

// PayloadHasSuffix applies the HasSuffix predicate on the "payload" field.
func PayloadHasSuffix(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldHasSuffix(FieldPayload, v))
}

// PayloadEqualFold applies the EqualFold predicate on the "payload" field.
func PayloadEqualFold(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldEqualFold(FieldPayload, v))
}

// PayloadContainsFold applies the ContainsFold predicate on the "payload" field.
func PayloadContainsFold(v string) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.FieldContainsFold(FieldPayload, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DictionaryIndexEntry) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DictionaryIndexEntry) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DictionaryIndexEntry) predicate.DictionaryIndexEntry {
	return predicate.DictionaryIndexEntry(sql.NotPredicates(p))
}
